- README.md
- test/presubmit-tests.sh
> Add link to code of conduct, test Prow

- OWNERS
Adding myself as reviewer and approver
> Adding myself to owners

- cmd/channel/main.go
- cmd/dispatcher/main.go
- pkg/channel/env/environment.go
- pkg/channel/env/environment_test.go
- pkg/common/env/constants.go
- pkg/common/k8s/context.go
- pkg/common/k8s/tracing.go
- pkg/common/k8s/tracing_test.go
- pkg/controller/env/environment.go
- pkg/controller/env/environment_test.go
- pkg/controller/kafkachannel/dispatcher.go
- pkg/controller/kafkasecret/channel.go
- pkg/controller/test/data.go
Fixes #22
In order to have tracing (via the config-tracing configmap) work properly, a call to SetupDynamicPublishing() needs to be made.  This adds those calls to the main functions of the controller and dispatcher.
> Add InitializeTracing function and call it from controller and dispatcher main

- .codecov.yaml
Related to https://github.com/knative-sandbox/.github/pull/20
/cc @mattmoor
> enable code coverage

- hack/release.sh
Fixes #
-
-
-
```release-note
```
**Docs**
> Respect that we have different things to release now

- config/channel/consolidated/deployments/webhook.yaml
- config/source/deployments/controller.yaml
related: https://github.com/knative/eventing/pull/4168/files
/hold
> Porting 4169 to here

- .gitattributes
- README.md
- config/channel/distributed/200-eventing-kafka-configmap.yaml
- config/channel/distributed/README.md
- pkg/channel/distributed/common/kafka/producer/producer_test.go
- pkg/channel/distributed/controller/kafkachannel/controller_test.go
- pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
- pkg/channel/distributed/controller/kafkachannel/topic_test.go
- pkg/channel/distributed/controller/kafkasecret/controller_test.go
- pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
- pkg/channel/distributed/controller/testing/data.go
- pkg/channel/distributed/controller/testing/factory.go
- pkg/channel/distributed/controller/testing/lister.go
- pkg/channel/distributed/controller/testing/mock.go
- pkg/channel/distributed/receiver/channel/channel_test.go
- pkg/channel/distributed/receiver/producer/producer_test.go
- pkg/channel/distributed/receiver/testing/channel.go
- pkg/channel/distributed/receiver/testing/constants.go
- pkg/channel/distributed/receiver/testing/event.go
- pkg/channel/distributed/receiver/testing/message.go
- pkg/channel/distributed/receiver/testing/mock.go
Adding .gitattributes with coverage exclusion rules and renaming some test/ packages to testing/ for alignment with rules and general consistency.
> refactor test/ dirs to testing/ for inclusion in coverage skip rules

- config/source/configmaps/observability.yaml
Fixes #
- all other configmaps are in `knative-sources`
```release-note
```
**Docs**
> Align the config with the others on the same namespace

- config/channel/consolidated/deployments/dispatcher.yaml
- config/source/configmaps/observability.yaml
- config/source/roles/clusterrole.yaml
- config/source/webhooks/kafka.yaml
- Fix release labels in Kafka components
To be backported to 0.18 and 0.17
```release-note
Fixed release labels for some Kafka related resources
```
**Docs**
> Fix release labels in Kafka components

- pkg/source/reconciler/source/kafkasource.go
- pkg/source/reconciler/source/resources/receive_adapter.go
Signed-off-by: runzexia <root@junwuhui.cn>
Fixes #75 https://github.com/knative/eventing-contrib/pull/1619
-
-
-
```release-note
```
**Docs**
> use knative/pkg utils

- README.md
- config/channel/distributed/README.md
- docs/kind_kafka_cluster.md
- pkg/channel/consolidated/README.md
- pkg/channel/distributed/README.md
- pkg/channel/distributed/common/kafka/README.md
- pkg/channel/distributed/common/metrics/README.md
- pkg/channel/distributed/controller/README.md
- pkg/channel/distributed/controller/kafkasecretinjection/README.md
- pkg/channel/distributed/dispatcher/README.md
- pkg/channel/distributed/receiver/README.md
- pkg/source/README.md
Produced via:
```shell
prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github | grep -v docs/cmd/)
```
/cc matzew slinkydeveloper
/assign matzew slinkydeveloper
> [Automated] Format markdown

- .github/workflows/knative-boilerplate.yaml
- .github/workflows/knative-donotsubmit.yaml
- .github/workflows/knative-go-build.yaml
- .github/workflows/knative-go-test.yaml
- .github/workflows/knative-security.yaml
- .github/workflows/knative-stale.yaml
- .github/workflows/knative-style.yaml
- .github/workflows/knative-verify.yaml
Produced via:
```shell
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
"${GITHUB_WORKSPACE}/main/.github/workflows/"
```
/cc matzew slinkydeveloper
/assign matzew slinkydeveloper
> [Automated] Update actions

- go.mod
- pkg/apis/sources/v1alpha1/kafka_conversion.go
- pkg/apis/sources/v1alpha1/kafka_types.go
- pkg/apis/sources/v1alpha1/roundtrip_test.go
- pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/sources/v1beta1/fuzzer.go
- pkg/apis/sources/v1beta1/roundtrip_test.go
- test/lib/listers.go
- vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
- vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/compatibility.go
- vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
- vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
- vendor/modules.txt
Fixes #127
-
-
-
```release-note
🐛 v1beta1 KafkaSource conditions are now fully preserved 
```
**Docs**
> DeepCopy the entire set of conditions

- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
- pkg/channel/consolidated/reconciler/controller/resources/service.go
- pkg/channel/consolidated/reconciler/controller/resources/service_test.go
- pkg/channel/distributed/controller/kafkachannel/channel.go
- 🧽 Update or clean up current behavior
> Use the network.GetServiceHostname helper

- pkg/source/adapter/adapter.go
- Offsets are now committed to the broker
-
-
```release-note
🐛 Offsets are now committed to the broker using the autocommit policy (default flush interval is 1s)
```
**Docs**
> use default autocommit configuration

- config/source/resources/kafkabinding.yaml
- pkg/apis/bindings/v1alpha1/kafka_conversion.go
- pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
- Cherrypick https://github.com/knative/eventing-contrib/pull/1651
- No fuzzing tests like KafkaSource. Created https://github.com/knative-sandbox/eventing-kafka/issues/145 for that
-
```release-note
- 🐛 Fix bug
Fix KafkaBinding conversion
```
**Docs**
> Fix KafkaBinding conversion

- pkg/apis/bindings/v1alpha1/roundtrip_test.go
- pkg/apis/bindings/v1beta1/fuzzer.go
- pkg/apis/bindings/v1beta1/roundtrip_test.go
Fixes #145
-
-
-
```release-note
```
**Docs**
> add kafka binding fuzzer

- go.mod
- go.sum
- vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
- vendor/modules.txt
running:
```
./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh 
```
> Updates to latest

- .github/workflows/kind-e2e.yaml
Fixes #
-
-
-
```release-note
```
**Docs**
> Adding KinD for e2e

- config/channel/consolidated/deployments/dispatcher.yaml
Port https://github.com/knative/eventing-contrib/pull/1660
> Port https://github.com/knative/eventing-contrib/pull/1660

- pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
- pkg/source/adapter/adapter_test.go
Fixes #
- updating b/c of https://github.com/knative/eventing/pull/4465 
-
-
```release-note
```
**Docs**
> No longer use deprecated calls

- pkg/common/consumer/consumer_handler.go
Fixes #178
- Let the inflight messages to properly terminate when the session closes 
- 
-
```release-note
```
**Docs**
> [common] don't use session context to send messages

- OWNERS
Add Ahmed Abdalla to reviewers
> Add Ahmed Abdalla to reviewers

- OWNERS
Add myself as approver and reviewer
Based on a discussion we had before (already approver in eventing and eventing-contrib)
> Add myself as approver and reviewer

- pkg/channel/consolidated/utils/util_test.go
Fixes #
- test clean up
-
-
```release-note
```
**Docs**
> Update tests to refect we don't have the consumer mode, since ages

- cmd/channel/distributed/receiver/main.go
- pkg/channel/distributed/dispatcher/dispatcher/handler.go
- pkg/channel/distributed/receiver/producer/producer.go
-🧽 Check debug log level before making calls that use the possibly-expensive zap.Any() call
> Check debug logging

- test/e2e-tests.sh
Fixes #
- ACK the new test jobs
-
-
```release-note
```
**Docs**
> ACK new test jobs

- pkg/source/client.go
- pkg/source/client_test.go
Add additional testcase, change how we default to plaintext SASL
> Defaulting to SASL plaintext wasn't working for consolidated channel

- test/e2e-tests.sh
Fixes #
- use namespace vars for secret script
```release-note
```
**Docs**
> Use namespace var, instead of hardcoded value

- pkg/channel/distributed/common/metrics/stats_reporter_test.go
Fixes #
- skip a flaky test, to reduce noise 
```release-note
```
**Docs**
> Skipping a flaky test

- config/channel/webhook/webhook-configuration.yaml
- config/source/webhooks/kafka.yaml
Fixes #
- Update Webhook Api to v1 
```release-note
```
**Docs**
> Update Webhook Api to v1

- pkg/apis/bindings/v1alpha1/kafka_conversion.go
- pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
- pkg/apis/bindings/v1alpha1/kafka_lifecycle.go
- pkg/apis/bindings/v1alpha1/kafka_lifecycle_test.go
- pkg/apis/bindings/v1alpha1/kafka_types.go
- pkg/apis/bindings/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/bindings/v1beta1/kafka_lifecycle.go
- pkg/apis/bindings/v1beta1/kafka_lifecycle_test.go
- pkg/apis/bindings/v1beta1/kafka_types.go
- pkg/apis/bindings/v1beta1/zz_generated.deepcopy.go
- pkg/source/client.go
- pkg/source/client_test.go
- pkg/source/reconciler/source/resources/receive_adapter.go
- pkg/source/reconciler/source/resources/receive_adapter_test.go
- test/e2e-tests.sh
- test/e2e/kafka_binding_test.go
- test/e2e/kafka_source_reconciler_test.go
- test/e2e/kafka_source_test.go
* Add kafkasource SASL Type
* Add unit tests for NewConfig in source client
* Add tests, lifecycle, e2e test
* Fix v1alpha1 conversion, tests
* Refactor tests
* Change kafkabinding sasltype json to 'type'
> Add kafkaSource saslType, e2e tests for auth (tls and sasl512) (#237)

- test/config/config-kafka-sasl.yaml
- test/config/config-kafka-tls.yaml
- test/e2e-common.sh
Fixes #
- more tweaks for `SYSTEM_NAMESPACE` 
```release-note
```
**Docs**
> Usage of more SYSTEM_NAMESAPCE in tests

- config/channel/consolidated/roles/dispatcher-clusterrole.yaml
Fixes #
- fixing bug where the dispatcher is not working 
```release-note
```
**Docs**
> Granting RBAC access for the leases

- config/channel/consolidated/roles/dispatcher-clusterrole.yaml
- pkg/channel/consolidated/kafka/admin.go
Fixes #
- porting two fixes to here, from master (https://github.com/knative-sandbox/eventing-kafka/pull/256 and https://github.com/knative-sandbox/eventing-kafka/pull/257)
```release-note
```
**Docs**
> [0.19] some backports

- config/source/100-deprecated-namespace.yaml
- test/e2e-common.sh
- 
-
-
```release-note
```
**Docs**
> add config creating knative-eventing ns

- config/channel/consolidated/200-controller-serviceaccount.yaml
- config/channel/consolidated/200-dispatcher-serviceaccount.yaml
- config/channel/consolidated/201-clusterrolebinding.yaml
- config/channel/consolidated/deployments/controller.yaml
- config/channel/consolidated/deployments/dispatcher.yaml
- config/channel/consolidated/roles/addressable-resolver-clusterrole.yaml
- config/channel/consolidated/roles/channelable-manipulator-clusterrole.yaml
- config/channel/consolidated/roles/controller-clusterrole.yaml
- config/channel/consolidated/roles/dispatcher-clusterrole.yaml
- config/channel/distributed/100-addressable-resolver-clusterrole.yaml
- config/channel/resources/kafkachannel-crd.yaml
- config/channel/webhook/webhook-clusterrole.yaml
- config/channel/webhook/webhook-clusterrolebinding.yaml
- config/channel/webhook/webhook-configuration.yaml
- config/channel/webhook/webhook-deployment.yaml
- config/channel/webhook/webhook-secret.yaml
- config/channel/webhook/webhook-service.yaml
- config/channel/webhook/webhook-serviceaccount.yaml
- config/source/100-deprecated-namespace.yaml
- config/source/100-namespace.yaml
- config/source/200-serviceaccount.yaml
- config/source/202-clusterrolebinding.yaml
- config/source/500-deprecated-controller.yaml
- config/source/deployments/controller-service.yaml
- config/source/deployments/controller.yaml
- config/source/resources/kafkabinding.yaml
- config/source/resources/kafkasource.yaml
- config/source/roles/clusterrole.yaml
- config/source/webhooks/kafka.yaml
- hack/release.sh
- change the release labels
/assign @pierDipi @travis-minke-sap
> Better reflection of this artifact on the release labels

- config/source/webhooks/kafka.yaml
- update last `v1beta1` to `v1` ...
```release-note
```
**Docs**
> We forgot one admissionregistration.k8s.io/v1beta1 update to v1

- go.mod
- go.sum
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
- pkg/channel/distributed/common/config/observability.go
- pkg/channel/distributed/common/config/observability_test.go
- pkg/channel/distributed/common/config/tracing.go
- pkg/channel/distributed/common/k8s/context.go
- vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
- vendor/knative.dev/pkg/configmap/manual_watcher.go
- vendor/knative.dev/pkg/injection/sharedmain/main.go
- vendor/knative.dev/pkg/metrics/config.go
- vendor/knative.dev/pkg/metrics/exporter.go
- vendor/knative.dev/pkg/test/mako/config/slack.go
- vendor/knative.dev/pkg/tracing/setup.go
- vendor/modules.txt
> Prepare for splitting configmap package.

- cmd/channel/distributed/dispatcher/main.go
- cmd/channel/distributed/receiver/main.go
- pkg/channel/distributed/common/config/configwatcher.go
- pkg/channel/distributed/common/config/configwatcher_test.go
- pkg/channel/distributed/controller/kafkachannel/channel.go
- pkg/channel/distributed/controller/kafkachannel/controller.go
- pkg/channel/distributed/controller/kafkachannel/dispatcher.go
- pkg/channel/distributed/controller/kafkachannel/kafkachannel.go
- pkg/channel/distributed/controller/kafkachannel/reconciler.go
- pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
- pkg/channel/distributed/controller/kafkachannel/topic.go
- pkg/channel/distributed/controller/kafkachannel/topic_test.go
- pkg/channel/distributed/controller/kafkasecret/controller.go
- pkg/channel/distributed/controller/kafkasecret/kafkachannel.go
- pkg/channel/distributed/controller/kafkasecret/receiver.go
- pkg/channel/distributed/controller/kafkasecret/reconciler.go
- pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
- pkg/channel/distributed/controller/kafkasecretinjection/reconciler.go
- pkg/channel/distributed/controller/testing/mock.go
- pkg/channel/distributed/receiver/producer/producer.go
-🎁  Use loggers from context in controller reconciler code (includes a traceid already provided by eventing)
> Add distributed traceid

- test/README.md
Fixes #
- fix instructions to run e2e tests locally
-
-
```release-note
```
**Docs**
> fix instructions to run e2e tests locally

- OWNERS
> Add steven0711dong to the owner list 

- pkg/source/reconciler/source/resources/receive_adapter.go
- 
-
-
```release-note
🧽 The KafkaSource dispatchers now expose metrics and profiling information 
```
**Docs**
> KafkaSource: expose dispatcher metrics and profiling data

- pkg/channel/consolidated/utils/util.go
- pkg/common/client/config.go
Fixes #356
- backport of #359 to 0.20
```release-note
- 🐛 Fix bug
Adding tls.enabled flag for public cert usage and allowing skipping CA/User certs and key
```
**Docs**
> [0.20] Backport of 359 to 0.20

- pkg/channel/consolidated/utils/util.go
- pkg/source/client.go
Fixes #356
- backport of #359 to 0.19
```release-note
- 🐛 Fix bug
Adding tls.enabled flag for public cert usage and allowing skipping CA/User certs and key
```
**Docs**
> [0.19] Backport of 359 to 0.19

- test/README.md
- Add skip-teardown flag instruction
- Add instruction to run the e2e mt source tests
-
```release-note
```
**Docs**
> slightly improve e2e doc

- go.mod
- go.sum
- vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
- vendor/modules.txt
Updating to latest, via
```
./hack/update-deps.sh --upgrade --release v0.21 && ./hack/update-codegen.sh
```
/assign @slinkydeveloper 
/assign @lberk 
can one review this please?
> Updating deps

- .github/CODEOWNERS
/hold
Depends on https://github.com/knative/community/pull/498
> add mtsource owners

- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
- pkg/channel/consolidated/dispatcher/dispatcher_test.go
- pkg/channel/consolidated/dispatcher/kafka_subscription.go
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
> [0.21] Backport of #509

- go.mod
- go.sum
- vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
- vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
- vendor/modules.txt
Fixes #
- man. upates for latest eventing core
-
-
```release-note
```
**Docs**
> Adding latest eventing deps

- pkg/source/adapter/adapter.go
- Call InitOffset only once per st adapter instance. 
-
-
```release-note
```
**Docs**
> Only run InitOffset once after the adapter has started

- pkg/common/client/config.go
Fixes #
-
-
-
```release-note
```
**Docs**
> do not print out  users' apikey

- config/channel/webhook/webhook-clusterrole.yaml
- config/source/single/roles/clusterrole.yaml
- like https://github.com/knative/eventing/pull/5501 
-
-
```release-note
source and channel webhook cluster role has update permission for namespaces/finalizers.
```
**Docs**
> Add permission to update namespace finalizer

- config/command/resources/RESET_OFFSET.md
- pkg/channel/distributed/README.md
- pkg/common/commands/resetoffset/README.md
- pkg/common/commands/resetoffset/controller/dataplane.go
Subtask of #588 to provide some initial user documentation README information.
- 🎁  Added user level information next to CRD definition.
- 🎁  Added developer level information next to Command source code.
- 🧽  Cleaned up current "distributed" KafkaChannel README which was a bit dated.
**Notes**
- The ResetOffset Controller is still "inactive" and has not been added to any Channels/Sources/etc.
- This PR is not intended to comprise the FULL set of documentation for the ResetOffset feature - still need to determine whether other external docs are required, etc.  This is just a beginning at the repo level README information.
> ResetOffset - Preliminary README Docs

- pkg/source/adapter/adapter.go
- pkg/source/adapter/adapter_benchmark_test.go
- pkg/source/mtadapter/adapter.go
- pkg/source/mtadapter/adapter_test.go
- :broom: we're shuffling the source.StatsReporter from knative.dev/pkg to knative.dev/eventing
- Right now we setup an alias which will allow the transition to be done smoothly
```release-note
NONE
```
**Docs**
> use source.StatsReporter from knative.dev/eventing

- pkg/source/adapter/adapter_test.go
Follow up to https://github.com/knative-sandbox/eventing-kafka/pull/764
> missed an import when switching over to eventing's source.StatsReporter

- pkg/apis/sources/v1beta1/kafka_lifecycle_mt.go
- pkg/apis/sources/v1beta1/mttest/kafka_lifecycle_mt_test.go
Fixes #
-
-
-
```release-note
```
**Docs**
> add missing condition types

- test/rekt/features/kafkasource/data_plane.go
- test/rekt/features/kafkasource/mt_data_plane.go
- test/rekt/features/kafkasource/readiness.go
- test/rekt/features/kafkatopic/readiness.go
- test/rekt/resources/kafkacat/kafkacat.go
- test/rekt/resources/kafkacat/kafkacat_test.go
- test/rekt/resources/kafkachannel/kafkachannel.go
- test/rekt/resources/kafkachannel/kafkachannel_test.go
- test/rekt/resources/kafkasource/kafkasource.go
- test/rekt/resources/kafkasource/kafkasource_test.go
- test/rekt/resources/kafkatopic/topic.go
- test/rekt/resources/kafkatopic/topic_test.go
- test/rekt/resources/resetoffset/resetoffset.go
- test/rekt/resources/resetoffset/resetoffset_test.go
- 🧽 Rely on go 1.16 embed feature to get YAML files
- 🧽 Use manifest.CfgFn when appropriate
-
```release-note
```
**Docs**
> Cleanup rekt tests.

- pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
- pkg/apis/messaging/v1beta1/kafka_channel_lifecycle.go
- pkg/apis/messaging/v1beta1/kafka_channel_types.go
- pkg/apis/messaging/v1beta1/kafka_channel_types_test.go
- pkg/apis/messaging/v1beta1/kafka_channel_validation.go
- updating code that was less or more copied over from the `Channel` in upstream eventing, and fixing minor things
```release-note
```
**Docs**
> Remove a bit of copy-paste from the upstream channel

- cmd/channel/distributed/dispatcher/main.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
- pkg/source/reconciler/binding/controller.go
- pkg/source/reconciler/mtsource/controller.go
- pkg/source/reconciler/source/controller.go
- 🧽 Update or clean up current behavior
/kind cleanup
```release-note
```
**Docs**
> Use `controller.Impl` tracker and cleanups

- pkg/common/kafka/sarama/sarama.go
Fixes #
- Make configmap reading func exported
-
-
```release-note
```
**Docs**
> Make configmap reading func exported

- cmd/source/controller/main.go
- cmd/source/mtcontroller/main.go
- config/source/common/configmaps/config-kafka-source-defaults.yaml
- config/source/multi/400-config-kafka-source-defaults.yaml
- config/source/single/400-config-kafka-source-defaults.yaml
- hack/tools.go
- hack/update-checksums.sh
- pkg/apis/sources/config/doc.go
- pkg/apis/sources/config/kafka_defaults.go
- pkg/apis/sources/config/kafka_defaults_test.go
- pkg/apis/sources/config/store.go
- pkg/apis/sources/config/store_test.go
- pkg/apis/sources/config/testdata/config-kafka-source-defaults.yaml
- pkg/apis/sources/v1beta1/kafka_defaults.go
- pkg/apis/sources/v1beta1/kafka_defaults_test.go
- vendor/knative.dev/pkg/configmap/hash-gen/main.go
- vendor/knative.dev/pkg/configmap/testing/configmap.go
- vendor/modules.txt
> [release-0.25] add Kafka defaults, starting with KEDA annotations (#855)

- config/source/multi/roles/clusterrole.yaml
Fixes #
- like  knative/eventing#5501
-
-
```release-note
🐛 multi-tenant source webhook cluster role has update permission for namespaces/finalizers.
```
**Docs**
> fix KafkaSource mt webhook RBAC

- pkg/apis/kafka/v1alpha1/reset_offset_validation.go
- pkg/apis/kafka/v1alpha1/reset_offset_validation_test.go
- pkg/apis/messaging/v1beta1/kafka_channel_validation.go
- pkg/apis/messaging/v1beta1/kafka_channel_validation_test.go
Fixes #862 
- 🐛  Add immutability checks to the KafkaChannel and ResetOffset Validation.
```release-note
Inherent immutability of KafkaChannel and ResetOffset spec fields is now enforced by the kafka-webhook.
```
> Add Immutability Validation

- test/config/monitoring.yaml
Fixes #
- updating to `:latest` 
```release-note
```
**Docs**
> latest of zipkin

- config/channel/post-install/clusterrole.yaml
- :broom: Adding finalizers and status subresources for KafkaChannel
```release-note
```
**Docs**
> Adding finalizers and status subresources for KafkaChannel storage version migrator

- CODE-OF-CONDUCT.md
- reverting changes to COC doc (see discussion [here](https://github.com/knative/serving/pull/12057#discussion_r718279987))
/assign @devguyio @lionelvillard
> Reverting coc changes

- config/source/post-install/clusterrole.yaml
- config/source/post-install/storage-version-migrator.yaml
- Fix  kafkasources API group
-
-
```release-note
```
**Docs**
> Fix version migration job pointing to the wrong CRD

- pkg/source/reconciler/source/kafkasource.go
- test/e2e/helpers/kafka_helper.go
- Attempt to fix the flaky KafkaSource update tests by waiting for the KafkaTopic to be ready
-
-
```release-note
```
**Docs**
> Wait for topic readiness after creation

- go.mod
- go.sum
- test/rekt/resources/kafkatopic/topic.go
- test/rekt/resources/resetoffset/resetoffset.go
- vendor/knative.dev/reconciler-test/pkg/k8s/job.go
- vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
- vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
- vendor/modules.txt
https://github.com/knative-sandbox/reconciler-test/pull/261
has breaking changes that this patch fixes.
> Fix rekt compile errors

- config/source/multi/roles/clusterrole.yaml
- config/source/single/roles/clusterrole.yaml
Fixes #
- removing duplicated definitions
-
-
```release-note
```
**Docs**
> Remove duplicated yaml anchors for simpler files

- test/e2e/helpers/kafka_source_test_helper.go
Fixes #
- as per title
```release-note
```
**Docs**
> Comment out test that always fails

- test/conformance/source_crd_rbac_test.go
Fixes #
- adding last missing "source conformance" test to kafka
-
-
```release-note
```
**Docs**
> Adding CRD / RBAC test

- test/config/100-strimzi-cluster-operator-0.26.0.yaml
- test/e2e-common.sh
Fixes #
- using latest strimzi, but staying on version 2.8.x 
```release-note
```
**Docs**
> Updating to 0.26 of Strimzi

- test/config/100-kafka-ephemeral-triple-3.0.0.yaml
- test/e2e-common.sh
Fixes #
-
-
-
```release-note
Updated CI run to use apache kafka 3.0.0 
```
**Docs**
> Hello Apache Kafka 3.0.0

- test/config/100-strimzi-cluster-operator-0.26.1.yaml
- test/e2e-common.sh
Fixes #
- updating to 0.26.1
-
-
```release-note
```
**Docs**
> New Strimzi images

- test/config.go
`resources.MessagingAPIVersion` is equal to
messaging.knative.dev/v1
/assign @aliok
> Fix ChannelFeatureMap since KafkaChannel is v1beta1 not v1

- pkg/apis/sources/v1beta1/kafka_validation.go
> Fix KafkaSource validation error for missing bootstrapServers

- go.mod
- go.sum
- vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
- vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
- vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
- vendor/modules.txt
Fixes #
-
-
-
```release-note
Fixes the following vulnerabilities: 
github.com/knative/pkg contains dependency that is subject to DoS attack. 
githun.com/kubernetes/utils contains a security issue that was discovered where a user may be able to create a container with subpath volume mounts to access files & directories outside of the volume, including on the host filesystem.
```
**Docs**
> fix vulnerabilities

- test/conformance/channel_status_test.go
Fixes #
- Remove a `skip`, committed [here](https://github.com/knative-sandbox/eventing-kafka/pull/713/files#diff-f15ed2a7c2f4f1f362da0b727b1d674933c0ac8ed4b221f7f8b26ca88bf694afR29)
```release-note
```
**Docs**
> Do not skip the status test

- pkg/common/constants/constants.go
This reverts commit ce66b2ecd67d52f46adc7dd90c2ac50b07100885.
Fixes #
- this unblocks other downstream things on the broker
-
-
```release-note
```
**Docs**
> Revert "Update constants.go (#1085)"

- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
By returning an error, we retry to reconcile the channel.
Fixes #1112 
- Retry on reconcile subscriber error
```release-note
The KafkaChannel controller retries to reconcile a subscriber when there is an error.
```
> [consolidated] Retry on reconcile subscriber error

- hack/release.sh
- Limit the concurrent builds of ko in the release script
> Limity release.sh ko concurrent builds

- pkg/channel/consolidated/dispatcher/consumer_message_handler.go
- pkg/channel/distributed/dispatcher/dispatcher/handler.go
- pkg/common/tracing/tracing.go
- pkg/common/tracing/tracing_test.go
- pkg/source/adapter/adapter.go
Backport from main.
```release-note
```
**Docs**
> [release-1.2] Backport upgrade tracing

- test/config/100-kafka-ephemeral-triple-3.1.0.yaml
- test/config/100-strimzi-cluster-operator-0.28.0.yaml
- test/e2e-common.sh
Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>
Fixes #
- as per title
-
-
```release-note
```
**Docs**
> Update to strimzi 0.28 and kafka 3.1

- test/rekt/resources/kafkacat/kafkacat_test.go
- test/rekt/resources/kafkasource/kafkasource_test.go
- test/rekt/resources/kafkatopic/topic_test.go
Fixes #
- as per title
-
-
```release-note
```
**Docs**
> Remove calling 'ExecuteLocalYAML', b/c it is deprecated

- test/upload-test-images.sh
In line with #1145 , this change would add flexibility to testing.
Fixes #
- as per title
-
-
```release-note
```
**Docs**
> Add KO_FLAGS to upload_test_images()

- test/e2e/helpers/kafka_helper.go
Fixes #
- util to be used on tests for creating kafka user for read/write/describe
```release-note
Test lib has a util to create Kafka user CRs now
```
**Docs**
> Adding a lib for creating a simple KafkaUser for a given topic

- pkg/source/reconciler/mtsource/kafkasource.go
Signed-off-by: aavarghese <avarghese@us.ibm.com>
Fixes #    
IBM Code Engine stress testing discovered issue with KafkaSource where resources don't get cleaned up causing scheduling to get stuck (flip floping from True to False ready states after 15+ hours)
Related to https://github.com/knative/eventing/pull/6440
- Finalization of KafkaSource now calls the MT Scheduler to deschedule placements which causes proper cleanup of internal resources.
```release-note
- Finalization of KafkaSource now calls the MT Scheduler to deschedule placements which causes proper cleanup of internal resources.
```
> [MT Scheduler] Deschedule placements on FinalizeKind

- test/e2e/channel_chain_test.go
- Skiap channel chain test as the conformance chain test has been deprecated.
-
-
```release-note
```
**Docs**
> Skip channel chain test

- README.md
Fixes #
- updates to README reflecting the MT source being the only component in here.
```release-note
```
**Docs**
> Simple reference to just the source and show new home for the channel 
