- Makefile
- pkg/common/kafka/admin/admin_kafka.go
- pkg/common/kafka/admin/admin_kafka_test.go
Fixes #12 
Added minimal stability fixes so that the "Kafka" use case behaves similar to the "EventHubs" use case when the Kafka Secret is missing or invalid.
Also re-added the Makefile which was accidentally removed.  We can refactor it out into hack scripts or something else at some point, but it still has useful development utilities (partial test runs with code coverage and such...)
> Handle missing or invalid kafka secrets

- pkg/channel/health/health.go
- pkg/channel/health/health_test.go
- pkg/common/health/health.go
- pkg/common/health/health_test.go
- pkg/dispatcher/health/health.go
- pkg/dispatcher/health/health_test.go
Fixes #18
Removed live HTTP server unit tests for health.go from dispatcher and channel (unnecessary duplication of testing between those and common).  Changed common health.go test to use a system-assigned port for the local HTTP server to avoid random port conflicts during testing.
> Remove fixed port for health tests

- cmd/channel/main.go
- cmd/dispatcher/main.go
Part of https://github.com/knative/community/issues/193.
Similarly to https://github.com/knative/pkg/pull/1693 in pkg, and in line with latest kubectl, drop `--master` flags in favour of `--server`.
> Use server flag for kubernetes server url

- pkg/controller/test/data.go
- pkg/controller/util/channel.go
- pkg/controller/util/channel_test.go
- pkg/controller/util/dispatcher.go
- pkg/controller/util/dispatcher_test.go
- pkg/controller/util/hash.go
- pkg/controller/util/hash_test.go
Fixes #52
Change the ChannelDnsSafeName and DispatcherDnsSafeName functions to return a value that includes a hash of the channel name and namespace, to prevent naming collisions.
> Improve dispatcher naming

- config/channel/distributed/400-deployment.yaml
Partially addresses #57 - will need to update the "consolidated" (eventing-contrib) channel deployments once that code is merge into this repo.
> add POD_NAME env var to distributed channel controller deployment

- contrib/test/e2e/helpers/kafka_helper.go
- contrib/test/lib/creation.go
- pkg/channel/consolidated/reconciler/controller/resources/service.go
- pkg/channel/distributed/common/health/health.go
- pkg/channel/distributed/common/health/health_test.go
- pkg/channel/distributed/common/k8s/util_test.go
- pkg/channel/distributed/common/kafka/admin/admin_custom_test.go
- pkg/channel/distributed/common/kafka/admin/admin_eventhub.go
- pkg/channel/distributed/common/kafka/admin/admin_eventhub_test.go
- pkg/channel/distributed/common/kafka/admin/eventhubcache/cache.go
- pkg/channel/distributed/common/kafka/admin/eventhubcache/cache_test.go
- pkg/channel/distributed/common/kafka/admin/eventhubcache/hubmanager.go
- pkg/channel/distributed/common/kafka/admin/eventhubcache/namespace_test.go
- pkg/channel/distributed/common/kafka/testing/mocks.go
- pkg/channel/distributed/common/metrics/stats_reporter.go
- pkg/channel/distributed/common/util/util.go
- pkg/channel/distributed/common/util/util_test.go
- pkg/channel/distributed/controller/kafkasecretinjection/reconciler.go
- pkg/channel/distributed/controller/kafkasecretinjection/state.go
- pkg/channel/distributed/controller/util/dns_test.go
- pkg/channel/distributed/controller/util/secret_test.go
- pkg/channel/distributed/dispatcher/dispatcher/handler.go
- pkg/channel/distributed/dispatcher/health/health_test.go
- pkg/channel/distributed/receiver/health/health_test.go
- pkg/channel/distributed/receiver/test/message.go
- pkg/channel/distributed/receiver/util/util_test.go
fmt fixes, done via:
```
gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print)
goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party | grep -v .pb.go | grep -v wire_gen.go)
```
> Some fmt lints

- config/channel/consolidated/deployments/controller.yaml
- config/channel/consolidated/deployments/dispatcher.yaml
Fixes #57 
Adding POD_NAME to consolidated channel controller/dispatcher deployments now that they are relocated from contrib.
> Add POD_NAME to consolidated channel deployments

- config/channel/distributed/200-eventing-kafka-configmap.yaml
- pkg/channel/distributed/dispatcher/README.md
- pkg/channel/distributed/receiver/README.md
- test/config/100-strimzi-cluster-operator-0.19.0.yaml
Fixes #
* running [misspell](https://github.com/client9/misspell)
```
export FILES=( $(find . -type f -not -path './vendor/*' -not -path './third_party/*' -not -path './.git/*') )
misspell -w "${FILES[@]}"
```
> running misspell

- go.mod
- go.sum
- vendor/modules.txt
Unpin github.com/Azure/go-autorest. The pin seems arbitrary, the version is old and stuff fails in pkg's CI: https://github.com/knative/pkg/pull/1819/checks?check_run_id=1274282107
> Drop unnecessary pin of go-autorest

- .ko.yaml
The `eventing-kafka` repository historically used varying ko base images dependent upon the needs of the "distributed" KafkaChannel implementation.  Now that this implementation is based on Sarama, and the `eventing-contrib` repo has been merged into this repo, we can and should switch back to the "standard" base image used previously by the eventing-contrib repo and now used by most of the sandbox repos.
> Revert custom .ko.yaml back to eventing-contrib value.

- pkg/channel/distributed/controller/constants/constants.go
- pkg/channel/distributed/controller/kafkachannel/dispatcher.go
- pkg/channel/distributed/controller/kafkasecret/receiver.go
- pkg/channel/distributed/controller/testing/data.go
The recent merge of https://github.com/knative-sandbox/eventing-kafka/pull/133 has broken the distributed kafka channel implementation.  It added new required environment variables to the receiver/dispatcher but failed to populate them in Deployment created by the controller.  This PR provides the missing logic to do so.
> Note - This was not caught by automated testing because we are still in the process of standing up our e2e (integration) tests.  All unit tests were/are passing.
> populate newly required env vars in receiver/dispatcher

- cmd/webhook/main.go
- pkg/channel/consolidated/webhook/webhook.go
Moving webhook code to a library allows using webhook configurations
as a library and can be consumed by alternative implementations.
- Allow using webhook configurations as a library
> Allow using webhook configurations as a library

- pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle.go
- pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle_test.go
- pkg/apis/messaging/v1beta1/kafka_channel_lifecycle.go
- pkg/apis/messaging/v1beta1/kafka_channel_lifecycle_test.go
Different KafkaChannel implementation might want to have different
conditions, this PR adds the ability to register custom conditions
like we did upstream in https://github.com/knative/eventing/pull/3545
for the Broker.
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
Fixes #26 
- Allow registering custom conditions for different channel implementation
> Allow registering custom conditions for different channel implementations

- test/e2e-tests.sh
- test/e2e/kafka_binding_test.go
- test/e2e/kafka_source_reconciler_test.go
- test/e2e/kafka_source_test.go
- 🧽 Remove the "source" tests from the distributed channel tests, as they are duplicated by the consolidated tests.  A future enhancement to separate the source tests into their own distinct test would probably be good but for now this at least avoids the glaring redundancy.
- 🐛 Increased timeout on channel teardown/cleanup for "ko delete" and added some namespace/kafkachannel logging to help diagnose a sporadic failure of the distributed tests
> E2e remove source from distributed

- pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
- pkg/channel/consolidated/reconciler/controller/resources/dispatcher_test.go
Fixes #171
- Add missing env vars
-
-
```release-note
- 🐛 Fix crash in the consolidated KafkaChannel namespaced dispatcher
```
**Docs**
> fix namespaced kafka dispacher crash

- cmd/channel/consolidated/dispatcher/main.go
- config/channel/consolidated/roles/dispatcher-clusterrole.yaml
Fixes https://github.com/knative/eventing-contrib/issues/1659
-  Disable KafkaChannel dispatcher leader election
-
-
```release-note
- 🐛 The consolidated KafkaChannel dispatcher does not attempt anymore to acquire a lease
```
**Docs**
Must to be backported to 0.17
> [consolidated] Disable KafkaChannel dispatcher leader election

- pkg/channel/distributed/controller/kafkachannel/channel.go
- pkg/channel/distributed/controller/kafkachannel/dispatcher.go
- pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
- pkg/channel/distributed/controller/kafkasecret/receiver.go
- pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
- pkg/channel/distributed/controller/testing/data.go
- pkg/channel/distributed/controller/util/finalizer.go
- pkg/channel/distributed/controller/util/finalizer_test.go
We were concerned that the distributed KafkaChannel could potentially hit an extremely rare (if even possible?) race condition whereby it is doing a normal Reconciliation on a resource that exists in K8S but was "being" deleted.  Therefore we'd like to add a small check for the resources Deletion Timestamp and force a re-reconciliation just in case.
> Note - The Dispatcher resources (Service / Deployment) are "cross-namespace" and thus have their own Finalizer in place and will not be modified to force re-reconciliation if the user removes the Finalizer.  Some additional state logging was added to be explicit about the handling of the resource during reconciliation.
> Add defensive coding around reconciling deleted resources.

- config/source/configmaps/observability.yaml
-
-
-
```release-note
- 🧽 Default KafkaSource log level is now "info"
```
**Docs**
> KafkaSource: set default zap logger level to "info"

- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/consolidated/dispatcher/dispatcher_test.go
- Consolidated KafkaChannel dispatcher now handles produced event synchronously 
-
-
```release-note
- 🧽 The consolidated KafkaChannel now relies by default on SyncProducer for safer event production.
```
**Docs**
> [Consolidated] Use SyncProducer to provide safer delivery  

- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/consolidated/utils/util.go
- pkg/source/client.go
- pkg/source/client_test.go
- test/e2e-tests.sh
- If no `saslType` is provided, we should default to "PLAIN" (the source only supports plain)
- moving code to one central place
- adding tests
```release-note
```
**Docs**
> Move AuthConfig code to one place and add tests

- pkg/channel/distributed/common/kafka/admin/admin_eventhub.go
- pkg/channel/distributed/common/kafka/admin/util/util.go
- pkg/channel/distributed/common/kafka/admin/util/util_test.go
- pkg/channel/distributed/controller/kafkachannel/topic.go
It seems that Strimzi can return normal Golang errors instead of Sarama TopicErrors (which are errors).  The distributed channel contains logic for "promoting" these to TopicErrors for consistent handling upstream.  This PR enhances that implementation to String match the normal Golang errors against the Sarama/Kafka error strings.  If a match is found then the promotion is accurately performed to a specific KError instead of just to ErrUnknown.
The specific use case which highlighted this was an edge case and was ultimately handled correctly by the reconciler, but the logging was somewhat confusing.  To reproduce manually do the following...
1. Create a KafkaChannel
2. Manually add some bogus finalizer to prevent deletion.
3. Delete the KafkaChannel
4. Review logs and see an error with …
> Upconvert kafka errors to sarama TopicError

- pkg/channel/distributed/common/k8s/util_test.go
- pkg/channel/distributed/controller/config/config_test.go
- pkg/channel/distributed/controller/env/environment_test.go
- pkg/channel/distributed/controller/util/dispatcher_test.go
- pkg/channel/distributed/controller/util/dns_test.go
- pkg/channel/distributed/controller/util/hash_test.go
- pkg/channel/distributed/dispatcher/env/environment_test.go
- pkg/channel/distributed/receiver/env/environment_test.go
There are a bunch of legacy "table" tests in the distributed KafkaChannel implementation which don't use the testing framework correctly and make it hard to debug the individual test case failures.  This PR corrects those tests.  No production code was changed in this PR.
> fix half-baked table tests

- test/e2e-tests.sh
For both `SASL` and `TLS` tests, these two VARs are `0`:
* `TEST_CONSOLIDATED_CHANNEL`
* `TEST_DISTRIBUTED_CHANNEL`
That means we run  CONSOLIDATED_PLAIN ... and the DISTRIBUTED ... :facepalm: 
This PR fixes that
> Ensure we do not accidently run the consolidated plain tests with AUTH is enabled 

- config/channel/distributed/300-eventing-kafka-configmap.yaml
- pkg/channel/distributed/common/config/configwatcher.go
- pkg/channel/distributed/common/config/constants.go
- pkg/channel/distributed/common/kafka/sarama/sarama.go
- pkg/channel/distributed/common/testing/constants.go
- test/e2e-tests.sh
Fixes #
- align name of the configmap with the consolidated
-
-
```release-note
```
**Docs**
> [distributed] Use same configmap name, for the channels

- config/channel/consolidated/configmaps/leader-election.yaml
- config/channel/consolidated/deployments/controller.yaml
- config/channel/consolidated/deployments/dispatcher.yaml
- config/channel/distributed/300-leaderelection-configmap.yaml
- config/channel/distributed/500-controller-deployment.yaml
- config/source/configmaps/leader-election.yaml
- config/source/deployments/controller.yaml
- pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
- pkg/channel/consolidated/reconciler/controller/resources/dispatcher_test.go
- with the global default of the `config-leader-election`, it is still possible to do some fine-tuning, via the `CONFIG_LEADERELECTION_NAME` env-var on the deployments (e.g. controllers/dispatchers)
```release-note
KafkaSource and KafkaChannel will be default use the `config-leader-election` CM for configs
```
**Docs**
> Go with the overall default of the leader election

- pkg/apis/bindings/v1alpha1/kafka_conversion.go
- pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
- pkg/apis/bindings/v1alpha1/kafka_lifecycle.go
- pkg/apis/bindings/v1alpha1/kafka_lifecycle_test.go
- pkg/apis/bindings/v1alpha1/kafka_types.go
- pkg/apis/bindings/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/bindings/v1beta1/kafka_lifecycle.go
- pkg/apis/bindings/v1beta1/kafka_lifecycle_test.go
- pkg/apis/bindings/v1beta1/kafka_types.go
- pkg/apis/bindings/v1beta1/zz_generated.deepcopy.go
- pkg/source/client.go
- pkg/source/client_test.go
- pkg/source/reconciler/source/resources/receive_adapter.go
- pkg/source/reconciler/source/resources/receive_adapter_test.go
- test/e2e-tests.sh
- test/e2e/kafka_binding_test.go
- test/e2e/kafka_source_reconciler_test.go
- test/e2e/kafka_source_test.go
Fixes #200 
Adds SASL mechanism support for the kafkasource, adds a variety of testing, including e2e testing with plain (no auth), sasl512 and tls
> Add kafkaSource saslType, e2e tests for auth (tls and sasl512)

- pkg/source/reconciler/source/resources/labels.go
- pkg/source/reconciler/source/resources/labels_test.go
- test/e2e/helpers/kafka_helper.go
- Label source name has a different spelling in [eventing repo](https://github.com/knative/eventing/blob/241af67e1844c9363869ca4141b910d0bc9819c6/pkg/reconciler/apiserversource/resources/labels.go#L28)
- We should keep things consistent because tooling may rely on these labels etc. In my case this makes hard to parse metric labels.
- Ping source btw seems to have its [own special label](https://github.com/knative/eventing/blob/241af67e1844c9363869ca4141b910d0bc9819c6/pkg/reconciler/pingsource/resources/labels.go#L28).
```release-note
NONE
```
> Fix label consistency

- pkg/source/reconciler/source/resources/labels.go
- pkg/source/reconciler/source/resources/labels_test.go
- test/e2e/helpers/kafka_helper.go
> [Backport] fix label consistency

- pkg/source/adapter/adapter.go
Fixes #
Missing Close() for unused response body blocked tcp connections from being reused within process scope. This significantly reduces performance.
- 🧽 Improved performance of delivering messages
> Close request body for tcp connection reuse

- cmd/channel/consolidated/dispatcher/main.go
- pkg/channel/consolidated/kafka/admin.go
- pkg/channel/consolidated/kafka/admin_test.go
- pkg/channel/consolidated/reconciler/controller/consumer_group_watcher.go
- pkg/channel/consolidated/reconciler/controller/consumer_group_watcher_test.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
- pkg/channel/consolidated/reconciler/testing/kafkachannel.go
Backport of #182 
Fixes #134
Fixes #98 
Fixes knative/eventing-contrib#1556
- Set subscription readiness based on consumer group status in the consolidated Kafka
- Set's KafkaChannel consolidated dispatcher to read-only
- Enables HA in KafkaChannel consolidated dispatcher
```release-note
- A bug was fixed in the consolidated KafkaChannel where subscriptions would show up in the channel's `status.subscribers` before the dispatcher becomes ready to dispatch messages for those subscribers.
- Consolidated KafkaChannel dispatcher's horizontal scalability works now seamlessly with reconciler leader election.
```
> Backport: Set subscription readiness based on consumer group status (#182)

- cmd/channel/distributed/dispatcher/main.go
- cmd/channel/distributed/receiver/main.go
- pkg/channel/distributed/common/config/observability.go
- pkg/channel/distributed/common/config/observability_test.go
- pkg/channel/distributed/common/health/health.go
- pkg/channel/distributed/common/health/health_test.go
- pkg/channel/distributed/common/metrics/stats_reporter.go
- pkg/channel/distributed/common/metrics/stats_reporter_test.go
Fixes #218 
- 🐛 The "live server" tests are not necessary for decent code coverage during unit testing; replaced with mocks
> Fix flaky metrics, health, and observability tests

- pkg/channel/distributed/controller/constants/constants.go
- pkg/channel/distributed/receiver/producer/producer.go
The health (liveness and readiness) checks in the distributed channel caused a restart of the pod in 25 seconds (10 + 3*5) if Sarama was not ready by that point.  The timeout for the TCP dialer defaults to 30 seconds (in sarama/config.go) so the pod would restart (and take any logging information with it) without the administration being able to see the error response in the logs.
- 🧽  Increase initial health check timeouts to cover the default Net.Dialer.Timeout that sarama uses when connecting via the broker string to 45 seconds (30 + 5*3)
> Increase health check timeouts to allow Sarama timeouts

- pkg/channel/consolidated/kafka/admin.go
Fixes #
- fixing verbose logger (especially the `Attempting to list consumer group` line)
```release-note
```
**Docs**
> Removing verbose info logger

- pkg/common/consumer/consumer_factory.go
- pkg/common/consumer/consumer_factory_test.go
- pkg/common/consumer/consumer_handler.go
- pkg/common/consumer/consumer_handler_test.go
Fixes #174
- Scope consumer group handler to a session. 
- Scope error channel to a consumer group 
-
```release-note
🐛 Fix crash in Kafka consumer when a rebalance occurs
```
**Docs**
> fix custom consumer group error channel lifecycle

- pkg/source/adapter/adapter.go
Someone reported that error in Slack, and the repetition of "occurred" caught my attention.
I also shortened the message while I was at it. Less is more.
```release-note
```
**Docs**
> Fix error format in adapter

- pkg/source/adapter/adapter.go
Fixes #
This PR works as a complement for [Pull 239](https://github.com/knative-sandbox/eventing-kafka/pull/239). 
Inorder to reuse TCP connection for HTTP requests with `KeepAlive: true`, request body MUST be read and closed manually. Otherwise, lots of tcp connections will be created and stays TIME_WAIT, resulting errors like "cannot assign requested address".
Without this code change, users may adjust sysctl parameters below as workaround:
```
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_fin_timeout=15
```
> Read resp body for connection reuse

- config/channel/distributed/300-eventing-kafka-configmap.yaml
- config/channel/distributed/500-controller-deployment.yaml
- pkg/channel/distributed/common/kafka/sarama/sarama_test.go
- pkg/channel/distributed/controller/config/config.go
- pkg/channel/distributed/controller/config/config_test.go
- pkg/channel/distributed/controller/kafkachannel/dispatcher.go
- pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
- pkg/channel/distributed/controller/kafkasecret/receiver.go
- pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
- pkg/channel/distributed/controller/testing/data.go
- pkg/channel/distributed/controller/testing/factory.go
- 🎁 Allow not having the cpu/memory resource requests and/or limits in the config-kafka configmap for eventing-kafka.receiver and eventing-kafka.dispatcher
- 🧽 Default to no limit for receiver and dispatcher (but still allow a limit if defined by the admin in the config-kafka configmap) and a reasonable (100m / 50Mi) initial request size based on empirical small-cluster and small-message-size testing.
> Remove default limits

- cmd/channel/distributed/dispatcher/main.go
- cmd/channel/distributed/receiver/main.go
- pkg/channel/distributed/common/kafka/admin/admin_kafka.go
- pkg/channel/distributed/common/kafka/consumer/consumer_test.go
- pkg/channel/distributed/common/kafka/producer/producer_test.go
- pkg/channel/distributed/common/kafka/sarama/sarama.go
- pkg/channel/distributed/common/kafka/sarama/sarama_test.go
- pkg/channel/distributed/controller/kafkachannel/reconciler.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
- pkg/channel/distributed/receiver/producer/producer.go
- pkg/common/client/config.go
- pkg/common/client/config_test.go
- pkg/common/client/sarama.go
- pkg/common/client/sarama_test.go
Related to #268
- Move some Sarama config related functions to a common package
- Make the `MergeSaramaSettings` function work with YAML-string instead of configmap
- Will follow up with more PRs that unify the behavior on both channels and the source around Sarama config by modifying `MergeSaramaSettings` as necessary and using it as the central place for Sarama config building
```release-note
```
**Docs**
> Move Sarama YAML related functions into common

- pkg/channel/distributed/controller/kafkachannel/controller_test.go
- pkg/channel/distributed/controller/kafkasecret/controller_test.go
The distributed KafkaChannel contains two controllers which each have a test of their `NewController()` functionality.  These tests were asserting the Controller name matched an expected value.  That name is populated by the **generated** code in `pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go` whose implementation can change.  This is causing problems with downstream builds related to knative-eventing [PR #4760](https://github.com/knative/eventing/pull/4760) where the logic for naming the controller is now using "." instead of "-" as a separator.  Therefore it's best for these tests not to expect any specific naming convention to account for the fact that the generated controller implementation might change.
- Adjust test to not expect a specific controller …
> Do not test controller name from generated source which can change.

- cmd/channel/distributed/dispatcher/main.go
- cmd/channel/distributed/receiver/main.go
- config/channel/distributed/300-eventing-kafka-configmap.yaml
- config/channel/distributed/300-kafka-secret.yaml
- config/channel/distributed/README.md
- pkg/channel/distributed/common/env/constants.go
- pkg/channel/distributed/common/kafka/constants/constants.go
- pkg/channel/distributed/controller/constants/constants.go
- pkg/channel/distributed/controller/kafkachannel/controller.go
- pkg/channel/distributed/controller/kafkachannel/dispatcher.go
- pkg/channel/distributed/controller/kafkachannel/reconciler.go
- pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
- pkg/channel/distributed/controller/kafkasecret/receiver.go
- pkg/channel/distributed/controller/testing/data.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
- pkg/channel/distributed/dispatcher/env/environment.go
- pkg/channel/distributed/dispatcher/env/environment_test.go
- pkg/channel/distributed/receiver/env/environment.go
- pkg/channel/distributed/receiver/producer/producer.go
Fixes #331
- Add `sasltype` to kafka secret to configure optional sasltype as `SCRAM-SHA-256` or `SCRAM-SHA-512`.
```release-note
Adding new optional field named `sasltype` to default kafka-secret to enable other Kafka SASL Methods than `PLAIN`. Supports `SCRAM-SHA-256` or `SCRAM-SHA-512`.
```
**Docs**
> #331 Add sasltype as optional secret parameter for kafka user configuration

- pkg/channel/distributed/dispatcher/dispatcher/handler.go
- pkg/channel/distributed/dispatcher/dispatcher/handler_test.go
- 🧽 Removed 400 ("Bad Request") from the list of responses in the distributed channel dispatcher's handler that indicate retries.
**Reasoning**
Retrying on a 400 response was a legacy behavior that was required due to the way the filter handler was consuming 5xx responses and returning 400 in their place.  This is no longer the case and "Bad Request" responses are not generally conditions that warrant retries, so that code has been removed.
Note that there are still several 4xx responses that do cause checkRetry to return true (namely 404, 409, and 429).  409 is required unless the e2e tests are changed, and 404/429 are left for their original reasons (noted in the comments for the checkRetry function).
> No retry on 400 response

- pkg/source/mtadapter/adapter.go
- Propagate source namespace to the st adapter.
-
-
```release-note
```
**Docs**
> [mt-source] Fix ce-source missing the namespace

- cmd/channel/distributed/dispatcher/main.go
- pkg/channel/distributed/dispatcher/constants/constants.go
-🧽 Increase the idle connection limits to the values used by the consolidated and in-memory channels
> Increase idle connection limits from 100/2 to 1000/100

- pkg/common/consumer/consumer_factory.go
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
In #263 the error channel is closed in a separate context of where it is created and it might cause race conditions during the teardown (one closes the error channel, but the consumer group is still running and tries to push to that channel).
This fix makes sure that we close the error channel effectively after `Consume` returns (when consume returns, sarama guarantees us that no consumer handler is running)
```
{"level":"info","ts":"2021-02-02T02:10:00.620Z","logger":"kafkachannel-dispatcher","caller":"consumer/consumer_handler.go:83","msg":"Failure while handling a message","knative.dev/pod":"kafka-ch-dispatcher-66776c4967-7lbpw","topic":"knative-messaging-kafka.kafka-stable-kn-retry-1.channel-0","partition":2,"offset":9732,"e …
```
> Fix race on error channel in consumer factory

- config/source/multi/201-adapter-clusterrole.yaml
- pkg/source/mtadapter/adapter.go
- pkg/source/mtadapter/adapter_test.go
- test/e2e-common.sh
- test/e2e/kafka_source_reconciler_test.go
Fixes #358
- Propagate the auth config down to the single-tenant adapter
-
-
```release-note
```
**Docs**
e2e tests are now passing (with https://github.com/knative-sandbox/eventing-kafka/pull/364). I'll enable PROW when both PR are merged.
/cc @steven0711dong
> Propagate the auth config down to the st adapter

- config/channel/consolidated/deployments/dispatcher.yaml
- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/consolidated/dispatcher/dispatcher_test.go
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
- pkg/common/consumer/consumer_handler.go
- pkg/common/consumer/consumer_handler_test.go
- pkg/source/adapter/adapter.go
this is a WIP/PoC for one half of a more immediate fix for the
'readySubscriber' issues in the kafkachannel.  This will need some of
the work that @devguyio is working on with lifting the network prober
to knative/pkg.  However, I'm about as far as I think I can get until
I know more about that implementation.
/hold
> Add http endpoint to communicate dispatcher readySubscriber status

- pkg/channel/consolidated/utils/util.go
- pkg/common/client/config.go
Fixes #356
- with public CA Certs we just need to "enable" TLS .... and we don't have to bother with the certs like for self-signed ones
```release-note
Adding tls.enabled flag for public cert usage and allowing skipping CA/User certs and key
```
**Docs**
> Adding check that requires us to just enable TLS, no need for custom certs

- pkg/apis/sources/v1beta1/kafka_validation.go
- pkg/apis/sources/v1beta1/kafka_validation_test.go
Change the validation of the kafkasource api to allow for changing the
topics/servers after creation
> Allow v1beta1 stkafkasource topics & bootstrapservers to be mutable

- config/source/multi/201-adapter-clusterrole.yaml
- pkg/common/scheduler/statefulset/autoscaler.go
- pkg/common/scheduler/statefulset/snapshot.go
- pkg/common/scheduler/statefulset/snapshot_test.go
- pkg/source/adapter/adapter.go
- pkg/source/mtadapter/adapter.go
- test/e2e-common.sh
- Limit scaling down the adapter to the last pod with placed "vpods" 
- Temporarily disable cancelling single-tenant adapters. See https://github.com/knative-sandbox/eventing-kafka/issues/382
- 
```release-note
```
**Docs**
source e2e tests are passing ... locally. Let's see if Prow is happy.
> [mtsource] don't kill pods with placed vpods

- pkg/source/reconciler/source/config_watcher.go
Address the comment by @eric-sap in https://github.com/knative-sandbox/eventing-kafka/pull/337#discussion_r573926042
- Just get rid of maybeAppendVar func as it is too complex for a simple thing
- Didn't want to make the same function in knative/eventing public
```release-note
```
**Docs**
> Get rid of maybeAppendVar func

- pkg/channel/consolidated/reconciler/controller/consumer_group_watcher.go
- pkg/channel/consolidated/reconciler/controller/controller.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
- pkg/common/constants/constants.go
Fixes #393
- Replace hardcoded `config-kafka` string with proper constant
- Fix a panic: null check `consumerGroupWatcher`
- Fix a block: `consumerGroupWatcher.terminate()` doesn't block forever anymore
Please review commit by commit.
```release-note
```
**Docs**
> Consolidated channel watch config kafka

- pkg/apis/sources/v1beta1/kafka_validation.go
- pkg/apis/sources/v1beta1/kafka_validation_test.go
- test/e2e/kafka_source_test.go
- test/lib/creation.go
- 🧽 Update or clean up current behavior
```release-note
The kafkasource now allows for mutable fields for:
- Topics 
- BootstrapServers 
- Sink
- Net
- CloudEventOverrides
Previously, after creation, all fields were immutable.
```
> Expand number of kafkasource fields that are now mutable, add e2e tests

- config/channel/consolidated/500-webhook-hpa.yaml
- config/channel/distributed/500-webhook-hpa.yaml
- config/channel/webhook/webhook-hpa.yaml
Fixes #
- Similar to "eventing core" (see https://github.com/knative/eventing/pull/4792/files), I am adding HPA for the webhook.
```release-note
Adding HorizontalPodAutoscaler and PodDisruptionBudget for the kafka webhook
```
**Docs**
> Adding HPA for webhook

- pkg/common/scheduler/statefulset/autoscaler.go
- pkg/source/mtadapter/adapter.go
- pkg/source/mtadapter/controller.go
- test/e2e-common.sh
- test/e2e/kafka_source_test.go
The e2e source tests are now passing when run on top of the mt source adapter. 
I opened several GH issues to track the various features that are missing/disabled to make this happened. 
- Single-tenant adapters are now properly shut down by the multi-tenant adapter
-
```release-note
```
**Docs**
> [mtsource] Enable stopping underlying st adapters when source is modified/removed.

- cmd/channel/distributed/dispatcher/main.go
- cmd/channel/distributed/receiver/main.go
- pkg/channel/distributed/common/k8s/context.go
- pkg/channel/distributed/common/k8s/context_test.go
- pkg/channel/distributed/receiver/channel/channel.go
- pkg/channel/distributed/receiver/channel/channel_test.go
Refactoring distributed component `main`s to make them use more of the functionality in sharedmain.
I wasn't able to [debug](https://github.com/knative/eventing/blob/master/DEVELOPMENT.md#debugging-knative-controllers-and-friends-locally-with-intellij-idea) the receiver and dispatcher locally because they required me to provide additional stuff like Kube URL etc. Once I provided these, this time the debugging failed because of missing service account token.
Fixes #
- Use `ParseAndGetRESTConfigOrDie` of `knative/pkg` which handles in-cluster or out-of-cluster situations better than `BuildConfigFromFlags` of the same package
- Change above also made these `main`s more similar to other Knative controllers with injection (more effort needed in this area)
```release-note
``` …
> Refactor distributed component mains to handle Kubernetes config better

- pkg/common/scheduler/statefulset/autoscaler.go
- pkg/source/mtadapter/adapter.go
- pkg/source/mtadapter/adapter_test.go
- pkg/source/mtadapter/controller.go
- pkg/source/mtadapter/kafkasource.go
Similar to https://github.com/knative/eventing/pull/4511
Fixes https://github.com/knative-sandbox/eventing-kafka/issues/412
- The mt source adapter doesn't set any finalizers anymore, since updating the internal state never fails.
- Reenable scaling down
-
```release-note
- 🧽 The mt source adapter does not set the finalizers anymore
```
**Docs**
> [mtsource] remove finalizer in mtadapter

- .github/CODEOWNERS
Add TOC, eventing approvers and release leads as default owners.
See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax
> Add more approvers as default owners

- pkg/channel/consolidated/reconciler/controller/controller.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/reconciler/controller/lister.go
- pkg/channel/consolidated/status/status.go
- pkg/channel/consolidated/status/status_test.go
- 🐛 Fix bug of probing the dispatcher for subscription readiness after dispatcher pods change.
- Backport of #487 
```release-note
🐛 A bug fix was back ported to the consolidated channel so that subscriptions becomes eventually ready even when dispatchers scale up or down. 
```
> [v0.20] [Consolidated Channel] Backport of #487 

- test/e2e-upgrade-tests.sh
- Adding dummy e2e upgrade test to unblock the upgrade test job and backporting to the branch. The upgrade tests were added to main and are not really needed for this old release
> [v0.20] Adding dummy e2e-upgrade-test

- pkg/channel/consolidated/reconciler/controller/controller.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/reconciler/controller/lister.go
- pkg/channel/consolidated/status/status.go
- pkg/channel/consolidated/status/status_test.go
- pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/controller.go
- pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
- pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/controller.go
- pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
- pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
- pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
- pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
- pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
- pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/controller.go
- pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
- pkg/client/injection/reconciler/sources/v1beta1/kafkasource/controller.go
- pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
- test/e2e-upgrade-tests.sh
- 🐛 Fix bug of probing the dispatcher for subscription readiness after dispatcher pods change.
- Backport of #487 
```release-note
🐛 A bug fix was back ported to the consolidated channel so that subscriptions becomes eventually ready even when dispatchers scale up or down. 
```
> [v0.21] [Consolidated Channel] Backport of #487

- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
- pkg/channel/consolidated/dispatcher/dispatcher_test.go
- pkg/channel/consolidated/dispatcher/kafka_subscription.go
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
Backport #509
> [0.20] Backport of #509

- cmd/channel/distributed/dispatcher/main.go
- cmd/channel/distributed/receiver/main.go
- pkg/channel/distributed/common/config/secretwatcher.go
- pkg/channel/distributed/common/config/secretwatcher_test.go
- pkg/channel/distributed/receiver/producer/producer.go
Backport of #525 (Runaway CPU due to timed-out secret watcher)
> [0.21] Backport of #525

- pkg/common/consumer/consumer_handler.go
- 🐛 Cancel dispatching messages when consumer group session is closed
```release-note
- 🐛 Fix a bug in consolidate channel where deleting a KafkaChannel-backed Broker with events in flight blocks new subscriptions in SubscriptionNotMarkedReadyByChannel . 
```
> [v0.21] Cancel dispatching messages when consumer group session is closed

- cmd/channel/distributed/receiver/main.go
- 🐛  The SetAlive(true) function in the distributed receiver's main() was after the NewProducer() call.  This leads to a situation in which calling CreateSyncProducer() on the Sarama client can delay the SetAlive call long enough (several retries per broker in the array) that kubelet will kill the receiver pod, which is not generally useful and prevents the appropriate errors from being visible in the receiver log after the Sarama calls finish failing.  It has been moved to before the NewProducer() -- the readiness state is still false until the producer is properly connected, however.
> Receiver liveness before sarama calls

- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/common/consumer/consumer_handler.go
Fixes #629
-  Cancel dispatching messages when consumer group session is closed 
```release-note
- 🐛Fix a bug in consolidate channel where deleting a KafkaChannel-backed Broker with events in flight blocks new subscriptions in SubscriptionNotMarkedReadyByChannel . 
- 🐛Fix a bug in KafkaSource potentially sending duplicates when Kafka rebalancing occurs
```
**Docs**
> Make sure ConsumeClaim exit before rebalance.timeout

- config/source/multi/deployments/adapter.yaml
- config/source/multi/deployments/controller.yaml
- pkg/source/mtadapter/adapter.go
- pkg/source/mtadapter/adapter_test.go
- MaxResponseSize is now Container Memory request / # of source instances in container. Cap at 50MB 
-
-
```release-note
```
**Docs**
> Adjust MaxResponseSize based on the number of active stadapters

- .github/workflows/kind-e2e.yaml
- go.mod
- go.sum
Needed to bump to the latest reconciler-test, and is why we're seeing failures in https://github.com/knative-sandbox/eventing-kafka/pull/663
> Bump go to 1.16

- pkg/source/mtadapter/adapter.go
- pkg/source/mtadapter/adapter_test.go
https://github.com/knative-sandbox/eventing-kafka/pull/668 followup.
This is a quick fix until a proper solution is implemented.
- MaxResponseSize is per broker so lower its value based on the potential number of connected brokers (set to 6)
- 
-
```release-note
```
**Docs**
> [mtsource] MaxResponseSize considers the number of connected brokers

- go.mod
- go.sum
- vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
- vendor/modules.txt
- Adding latest eventing deps 
- Needed for #688 
/cc @matzew
> Update to latest eventing deps

- config/source/multi/deployments/adapter.yaml
- pkg/source/mtadapter/adapter.go
- pkg/source/mtadapter/adapter_test.go
Fixes #691
- Revert https://github.com/knative-sandbox/eventing-kafka/pull/668/files as MaxResponseSize does not work as expected (see #691 for an explanation)
- Beef up the adapter pod to be able to handle larger messages. Not a definitive number, we can adjust as we gather more data.
-
```release-note
```
**Docs**
> Revert to setting consumer.fetch options instead of MaxReponseSize

- pkg/channel/consolidated/dispatcher/consumer_message_handler.go
- pkg/channel/consolidated/dispatcher/dispatcher.go
Fixes #683 
Sample output:
```
kafkachannel_dispatcher_event_count{container_name="dispatcher",event_type="dev.knative.apiserver.resource.add",namespace_name="default",response_code="200",response_code_class="2xx",unique_name="kafka-ch-dispatcher-68895d8745-bd888bfba0cbe24fb46b24bb140e613a"} 2
kafkachannel_dispatcher_event_count{container_name="dispatcher",event_type="dev.knative.apiserver.resource.update",namespace_name="default",response_code="200",response_code_class="2xx",unique_name="kafka-ch-dispatcher-68895d8745-bd888bfba0cbe24fb46b24bb140e613a"} 3
kafkachannel_dispatcher_event_dispatch_latencies_bucket{container_name="dispatcher",event_type="dev.knative.apiserver.resource.add",namespace_name="default",response_code="200",response_code_class="2xx",unique_name="kafka-ch-dispatcher-68 …
```
> Support eventing metrics

- cmd/channel/distributed/dispatcher/main.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
- pkg/channel/distributed/receiver/producer/producer.go
- pkg/channel/distributed/receiver/producer/producer_test.go
- pkg/common/config/testing/util.go
This isn't directly tied to an issue, but the changes for #537 made a few things in the distributed channel's "reconfigure" function obsolete; in particular it used to be called when the configmap changed as well, which could require a new dispatcher.  Now the only possible changes are from the secret, which is limited to username/password/SASLtype.  Changing those settings does not require a new dispatcher, so this PR will remove that behavior.
I would leave this alone but there is also a bug in the way the new dispatcher is created which leaves the old dispatcher referenced in the dispatcher's controller.  The controller.NewController call uses the original dispatcher and nothing ever changes that, which is something that will cause a problem with some upcoming changes that include a …
> Remove creation of new dispatcher when secret changes

- test/conformance/channel_status_subscriber_test.go
- test/e2e/channel_dls_test.go
Quick investigation seems to point to https://github.com/knative/pkg/pull/2149 breaking the dls test creating a subscription pointing to a sink that does not exist: https://github.com/knative/eventing/blob/main/test/e2e/helpers/channel_dls_test_helper.go#L73
- Temporarily disable dls tests due to https://github.com/knative/pkg/pull/2149. 
-
-
```release-note
```
**Docs**
> skip dls test

- config/channel/webhook/webhook-deployment.yaml
The horizontalPodAutoscaler fails without set resources.
- Add resources (values taken from serving, similar to eventing webhook defaults)
- :bug: Allows for hpa to work for kafka-webhook
```release-note
The kafka-webhook deployment now sets resource requests and limits to enable hpa
```
> Add resource requests and limits to kafka-webhook

- go.mod
- go.sum
- pkg/source/reconciler/source/kafkasource.go
- vendor/knative.dev/control-protocol/pkg/reconciler/async_command_notification_store.go
- vendor/knative.dev/control-protocol/pkg/reconciler/connection_pool.go
- vendor/knative.dev/control-protocol/pkg/reconciler/connection_pool_option.go
- vendor/modules.txt
I need to pull in the latest control-protocol version which exposes interfaces in order to test new ResetOffset (Replay) work.  This PR includes the new version and a minor adjustment to the KafkaSource which is the only current user of the control-protocol.
🎁  Updated control-protocol to version with interfaces.
> Update control-protocol version

- pkg/channel/consolidated/dispatcher/consumer_message_handler.go
This is an improvement for #688 .
> Avoid copying msg when extracting the event type

- pkg/common/scheduler/scheduler.go
- pkg/common/scheduler/statefulset/autoscaler.go
- pkg/common/scheduler/statefulset/autoscaler_test.go
- pkg/common/scheduler/statefulset/scheduler.go
- pkg/source/reconciler/mtsource/controller.go
Fixes #699
- The statefulset autoscaler now attempts to compact vreplicas (MaxFillUp strategy only)
-
-
```release-note
🎁 The multi-tenant KafkaSource controller periodically attempts to relocate KafkaSource consumers to Statefulset pods with a lower ordinal
```
**Docs**
> [scheduler] Compact vreplicas

- pkg/channel/consolidated/utils/util.go
- pkg/channel/consolidated/utils/util_test.go
Fixes #
```
=== CONT  TestSingleStructuredEventForChannel/KafkaChannel-messaging.knative.dev/v1beta1
operation.go:95: Failed to get all KResources ready failed waiting for {TypeMeta:{Kind:Subscription APIVersion:messaging.knative.dev/v1} ObjectMeta:{Name:e2e-singleevent-subscription-structured GenerateName: Namespace:eventing-e2e24 SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]}} to become ready: timed out waiting for the condition
operation.go:116: Failed to get all test resources ready: failed waiting for {TypeMeta:{Kind:Subscription APIVersion:messaging.knative.dev/v1} …
```
> Fix no kafka channel address issue

- pkg/common/scheduler/statefulset/autoscaler.go
- pkg/common/scheduler/statefulset/autoscaler_test.go
- pkg/common/scheduler/statefulset/scheduler.go
- pkg/common/scheduler/statefulset/state.go
- pkg/common/scheduler/statefulset/state_test.go
Fixes https://github.com/knative-sandbox/eventing-kafka/issues/704
- Keep track of reserved placements until they are persisted in the CR status section. 
-
-
```release-note
🐛 The multi-tenant KafkaSource controller now avoids overcommitting the KafkaSource multi-tenant adapter
```
**Docs**
> [Scheduler] Prevent pod to be overcommitted

- test/rekt/features/kafkasource/readiness.go
- test/rekt/kafka_source_test.go
This will help fixing the e2e tests in eventing-autoscaler-keda
- Add basic KafkaSource readiness test. 
-
-
```release-note
```
**Docs**
> [rekt] KafkaSource readiness test requires a topic

- pkg/common/consumer/consumer_manager.go
- pkg/common/consumer/consumer_manager_test.go
- pkg/common/consumer/managed_group.go
- pkg/common/consumer/managed_group_test.go
This fixes a few bugs that cropped up due to #742 
- 🐛 The managedGroup lock/unlock was being allowed if no CommandLock struct was passed to processLock, even if it was already locked with a token.
- 🐛 CloseConsumerGroup was logging warnings indicating that cancelErrors and cancelConsume were nil when they, in fact, were not
- 🧽 Several places were still directly accessing the groups map instead of using the getGroup/setGroup/deleteGroup functions
- 🧽 Added an interface for the managedGroup (now has managedGroupImpl) to clear up some confusion
The lock/unlock bug was due in no small part to functionality not being very well isolated to the appropriate structs (manager vs. managedGroup), so I have changed "managedGroup" to an interface that the manager now uses instead of arbitrarily …
> Fix stop start without locking

- config/channel/webhook/webhook-clusterrole.yaml
The KafkaChannel Webhook is currently broken and not performing validation/mutation/etc.  The logs show the following errors...
```
{"level":"debug","ts":"2021-07-01T20:57:15.279Z","logger":"kafkachannel-webhook.ValidationWebhook","caller":"controller/controller.go:502","msg":"Processing from queue validation.webhook.kafka.messaging.knative.dev (depth: 0)"}
{"level":"error","ts":"2021-07-01T20:57:15.281Z","logger":"kafkachannel-webhook.ValidationWebhook","caller":"controller/controller.go:549","msg":"Reconcile error","duration":0.001437821,"error":"failed to fetch namespace: namespaces \"knative-eventing\" is forbidden: User \"system:serviceaccount:knative-eventing:kafka-webhook\" cannot get resource \"namespaces\" in API group \"\" in the namespace …
```
> Missing webhook rbac

- config/channel/webhook/webhook-clusterrole.yaml
This PR is a backport of the fix in #751 to correct this problem on the release-0.24 branch which is also broken.
```release-note
- 🐛. Add missing RBAC (get namespaces) to KafkaChannel Webhook ClusterRole to satisfy new implementation. 
```
> Missing webhook rbac (backport)

- cmd/channel/distributed/dispatcher/main.go
- pkg/channel/distributed/dispatcher/constants/constants.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
- pkg/channel/distributed/dispatcher/testing/factory.go
- pkg/channel/distributed/dispatcher/testing/kafkachannel.go
- pkg/common/consumer/consumer_manager.go
- pkg/common/consumer/consumer_manager_test.go
- pkg/common/consumer/managed_group.go
- pkg/common/consumer/managed_group_test.go
- pkg/common/consumer/testing/mocks.go
Subtask of #588 to update the "subscribers" section of the status block for KafkaChannel resources when a ConsumerGroup is started or stopped.
🎁  Added Go channel notification option to the KafkaConsumerGroupManager (GetNotificationChannel) so that external entities may be informed of changes to a managed ConsumerGroup's status (create/start/stop/close)
🎁. Modified the distributed Dispatcher's KafkaChannel controller to use this new channel from the Manager and call EnqueueKey in order to trigger a reconciliation when Consumer Groups are started or stopped.
🎁  Modified the distributed Dispatcher's UpdateSubscriptions() call to return a map of status infomation that includes "stopped," so that the reconciler can use that information to update the subscribers status block properly. …
> Change kafkachannel status when paused

- pkg/common/kafka/sarama/batch_get_offsets.go
- pkg/common/kafka/sarama/batch_get_offsets_test.go
- pkg/source/client/offsets.go
InitOffsets can take a long time (several seconds, sometimes minutes), when the number of partitions is high (> 500), due to Sarama inability to batch OffsetFetch requests. 
- batch OffsetFetch requests, one per leading broker. 
- 
-
```release-note
```
**Docs**
> [Source] Optimize InitOffsets

- cmd/channel/distributed/controller/main.go
- config/channel/distributed/100-resetoffset-clusterrole.yaml
- config/channel/distributed/200-controller-clusterrolebinding.yaml
- config/channel/distributed/300-resetoffset-crd.yaml
- config/channel/distributed/500-webhook-deployment.yaml
- pkg/channel/distributed/README.md
- pkg/common/kafka/sarama/sarama_test.go
Subtask of #588 to enable ResetOffset support in the Distributed KafkaChannel.
The ResetOffset feature is nearing completion,  only lacking some final docs and e2e tests, and is ready to be enabled in the distributed KafkaChannel.  Once it has had some soak time, and the primary contributors to the Consolidated KafkaChannel are ready, it can be integrated/enabled there as well. 
- 🎁  Configure ResetOffset Controller with custom mappers for "distributed" KafkaChannel and start with KafkaChannel controller.
- 🎁  Include ResetOffset configuration in Distributed KafkaChannel config yaml.
- 🎁  Add a note in Distributed KafkaChannel README indicating support for ResetOffset. 
```release-note
🎁  Enabled support for ResetOffset CRD in distributed KafkaChannel, see …
```
> Enable ResetOffset in Distributed KafkaChannel

- config/command/resetoffset/README.md
Simple README fix to correct information on specifying offset times outside the retention window.
- 🐛  Previous information was incorrect regarding behavior of specifying an offset time outside the retention window.
> Correct ResetOffset README

- pkg/channel/distributed/controller/kafkachannel/reconciler.go
- pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
Fixes #774
Handle Kafka AdminClient failures by requeuing the KafkaChannel instead of panic/crashing.  Note... KafkaChannel will remain in perpetual reconcile/finalize loop until underlying Kafka connection issue is resolved.  If the user is intending to delete a KafkaChannel instance whose backing Kafka cluster has been torn down, they will need to manually remove the Finalizer from the KafkaChannel to escape this loop.  This is as intended ; )
-🐛  Throw and handle Kafka AdminClient creation error instead of just logging error and continuing until NPE occurs.
> [distributed KafkaChannel] Kafka AdminClient Error Handling

- pkg/channel/distributed/controller/kafkachannel/dispatcher.go
- pkg/channel/distributed/controller/kafkachannel/receiver.go
- pkg/channel/distributed/controller/testing/data.go
It is useful in production environments to be able to identify KafkaChannel Dispatcher Pods via a label.  Currently we have labels on the Deployments but not the Pods.  This PR fixes that by applying the labels in both places.
- 🧽  Enhance the Controller logic for creating Receiver/Dispatcher Deployments so that the labels are applied to resulting Pods as well.
> [distributed KafkaChannel] Add receiver/dispatcher labels to Pods as well as Deployments

- test/e2e/helpers/kafka_helper.go
The 1.6.0 version includes built-in retrying.
Fixes #789
> Upgrade KafkaCat image used in KafkaSource e2e tests

- cmd/channel/distributed/dispatcher/main.go
- cmd/channel/distributed/receiver/main.go
- pkg/channel/distributed/common/kafka/util/util.go
- pkg/channel/distributed/common/kafka/util/util_test.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
- pkg/common/consumer/consumer_manager.go
- pkg/common/consumer/consumer_manager_test.go
- pkg/common/consumer/testing/mocks.go
Fixes #794 
- 🧽  Restructure Dispatcher main() to create Controller prior to SecretWatcher.
- 🧽  Change Dispatcher's SecretObserver to be a factory capable of requeueing KafkaChannels.
- 🧽  Add util function to convert from GroupId back to Subscription.UID.
- 🧽  Return errors from Dispatcher Controller Reconcile() to requeue on failure.
- 🧽  Create new ReconfigureError type to contain the failed ConsumerGroup IDs
- 🧽  Dispatcher.SecretChanged() should handle ReconfigureErrors by removing failed ConsumerGroups from Dispatcher.subscribers so that the next reconcile will not ignore them (as being previously closed)
- 🐛 Dispatcher.Reconfigure() bug fixed so that "paused" (stopped) aren't restarted.
- 🧽  Dispatcher.Reconfigure() tracks failed ConsumerGroup IDs and returns new ReconfigureError …
> fix-reconfigure-and-reconciliation-issues

- hack/release.sh
as per title 
- separation of CRDs, like on eventing
-
-
```release-note
Separated CRDs to extra, additional yaml manifest (similar to eventing)
```
**Docs**
> Separate CRDs, like we have on eventing core

- pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
Removes a hack/todo from between 0.22 and 0.23 release. Reference PR: 
https://github.com/knative-sandbox/eventing-kafka/commit/59b7a9b1bce96c025ed348e494da0b99b22cff33#diff-b1219d1afc23409422ab316a2b695a33d92ec74fcc53b98691e9cd3058d8a106L35-R42
- remove hard coded `SubscribableDuckVersionAnnotation` 
-
-
```release-note
```
**Docs**
> Address TODO from releases 0.22 and 0.23

- pkg/source/mtadapter/controller.go
- pkg/source/mtadapter/kafkasource.go
Fixes #810 
-
-
-
```release-note
🐛 Remove confusing error message `Kafka source is not ready`. This error is returned as an event regardless the Kafka source has any real issue or not and users should not see this error message unless it is a legitimate error or it is an error they can fix. 
```
**Docs**
> removing confusing error message

- pkg/source/adapter/adapter.go
- pkg/source/adapter/message.go
- pkg/source/mtadapter/adapter.go
- pkg/source/reconciler/source/resources/receive_adapter.go
- test/e2e/kafka_source.go
- test/lib/resources/kafka.go
- test/rekt/features/kafkasource/data_plane.go
- test/rekt/resources/kafkasource/kafkasource.go
- test/rekt/resources/kafkasource/kafkasource.yaml
- test/rekt/resources/kafkasource/kafkasource_test.go
Fixes #804
- KafkaSource does not ignore `ceOverrides` anymore
-
-
```release-note
🎁 KafkaSource now supports ceOverrides.
```
**Docs**
> KafkaSource supports ceOverrides

- config/channel/resources/kafkachannel-crd.yaml
Fixes #744
- Make `status.address` optional in KafkaChannel CRD
- It is already marked as optional in the API code
- Check https://github.com/knative-sandbox/eventing-kafka/issues/744 for more details
```release-note
- 🐛 Fix bug: `status.address` of KafkaChannel is not required anymore, thus conditions are reflected successfully in case of an early stage error
```
**Docs**
> Make status.address optional in the KafkaChannel CRD

- cmd/source/controller/main.go
- cmd/source/mtcontroller/main.go
- config/source/common/configmaps/config-kafka-source-defaults.yaml
- config/source/multi/400-config-kafka-source-defaults.yaml
- config/source/single/400-config-kafka-source-defaults.yaml
- hack/tools.go
- hack/update-checksums.sh
- pkg/apis/sources/config/doc.go
- pkg/apis/sources/config/kafka_defaults.go
- pkg/apis/sources/config/kafka_defaults_test.go
- pkg/apis/sources/config/store.go
- pkg/apis/sources/config/store_test.go
- pkg/apis/sources/config/testdata/config-kafka-source-defaults.yaml
- pkg/apis/sources/v1beta1/kafka_defaults.go
- pkg/apis/sources/v1beta1/kafka_defaults_test.go
- vendor/knative.dev/pkg/configmap/hash-gen/main.go
- vendor/knative.dev/pkg/configmap/testing/configmap.go
- vendor/modules.txt
- Add new config-kafka-source-defaults configmap to be used by the defaulting mutating webhook 
- When autoscaler is enabled in the configmap, the defaulting webhook automatically adds KEDA annotations.
-
```release-note
- 🎁Autoscaling annotations can now be automatically added to KafkaSource objects. See the documentation for more details. 
```
**Docs**
See https://github.com/knative/docs/issues/4181
/cc @steven0711dong @matzew @zroubalik
> Add Kafka Source defaults, starting with KEDA annotations

- pkg/common/kafka/offset/offsets.go
- pkg/common/kafka/offset/offsets_test.go
- pkg/source/reconciler/mtsource/kafkasource.go
- pkg/source/reconciler/source/kafkasource.go
Fixes #
- Move initOffsets functionality to a common package - so that we can also use it in Channels later
- Do not create the admin client within the function. Get that as parameter. In channel impl (which will use this func soon), we already have the adminClient and we would just pass that as a parameter.
-
```release-note
```
**Docs**
> Move initOffsets functionality to a common package

- pkg/common/kafka/offset/offsets.go
- pkg/common/kafka/offset/offsets_test.go
- pkg/source/reconciler/mtsource/kafkasource.go
- pkg/source/reconciler/source/kafkasource.go
Cherry pick https://github.com/knative-sandbox/eventing-kafka/pull/883
- Return partition count in `initOffsets` function, but do not use it as it is not used in 0.24 codebase
> [0.24] Move initOffsets functionality to a common package

- config/source/multi/deployments/adapter.yaml
- pkg/common/scheduler/state/state.go
Signed-off-by: aavarghese <avarghese@us.ibm.com>
Fixes #881 
- Setting of number of replicas in StatefulSet Spec removed so that its value will be preserved when config is reapplied
- Nil checks for pod in State() before reading its Spec
```release-note
```
**Docs**
> Fix for [scheduler] Crash when creating state

- config/channel/consolidated/roles/controller-clusterrole.yaml
- Add delete deployment permission to the consolidated KafkaChannel controller.
```release-note
The consolidated KafkaChannel controller now has the permission to delete deployment which it needs to update the owner ref of its dispatcher deployment.
```
> Add delete deployment permission to kafka channel controller

- config/channel/post-install/200-clusterrole.yaml
- config/channel/post-install/400-kafkachannel-update-job.yaml
- config/channel/webhook/webhook-hpa.yaml
- config/source/common/configmaps/config-kafka-source-defaults.yaml
Fixes #
I ran into issues installing eventing, and I think this is the cause.
I was trying to install knative-eventing version 0.22.2 with the knative operator 0.25.2.
I also wanted to install kafka-source/kafka-channel/ and apache kafka broker
Here's a snippet of my operator manifest:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
name: knative-eventing
namespace: knative-eventing
spec:
version: "0.22.2"
additionalManifests: # Originally I mistakenly put "manifests:" here. After fixing it I ran into the same issue
- URL: https://github.com/knative-sandbox/eventing-kafka/releases/download/v${VERSION}/source.yaml
- URL: https://github.com/knative-sandbox/eventing-kafka/releases/download/v${VERSION}/channel-consolidated.yaml
- URL: …
```
> Fix release labels missing release version because of missing kafka prefix

- config/channel/post-install/clusterrole.yaml
- config/channel/post-install/placeholder.go
- config/channel/post-install/serviceaccount.yaml
- config/channel/post-install/storage-version-migrator.yaml
- :broom: Adding noop migrator for the `kafkachannels.messaging.knative.dev` to always have a migrator manifest on each release. 
```release-note
```
**Docs**
> Adding noop migrator for kafkachannels

- config/source/post-install/clusterrole.yaml
- config/source/post-install/placeholder.go
- config/source/post-install/serviceaccount.yaml
- config/source/post-install/storage-version-migrator.yaml
Similar to #903
- :broom: Adding noop migrator for the `kafkasources.sources.knative.dev` to always have a migrator manifest on each release. 
```release-note
storage version migrator for kafka source is now always part of the release
```
**Docs**
> Adding noop migrator for kafkasources

- pkg/source/mtadapter/adapter.go
- pkg/source/mtadapter/adapter_test.go
- pkg/source/mtadapter/controller.go
- pkg/source/mtadapter/kafkasource.go
- pkg/source/reconciler/common/finalizer.go
- pkg/source/reconciler/common/finalizer_test.go
- pkg/source/reconciler/mtsource/controller.go
- pkg/source/reconciler/mtsource/kafkasource.go
- pkg/source/reconciler/source/controller.go
- pkg/source/reconciler/source/kafkasource.go
- test/e2e-common.sh
Fixes #839
- Delete consumer group associated to KafkaSource instances marked for deletion  
-
-
```release-note
🎁 When a KafkaSource instance is deleted, the associated consumer group is also deleted
```
**Docs**
> delete consumer group when deleting source

- pkg/common/scheduler/README.md
Signed-off-by: aavarghese <avarghese@us.ibm.com>
Continuation of #768
- README
```release-note
```
**Docs**
> README for new MT Scheduler with pluggable policies

- .codecov.yaml
Similar to eventing, drop test directory from the codecov results
(getting a better understanding of unit testing coverage is currently
at)
> [trivial] Add test directory to ignored codecov directory

- cmd/channel/distributed/dispatcher/main.go
- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
- pkg/channel/consolidated/dispatcher/dispatcher_test.go
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
- pkg/common/consumer/consumer_factory.go
- pkg/common/consumer/consumer_factory_test.go
- pkg/common/consumer/consumer_handler.go
- pkg/common/consumer/consumer_manager.go
- pkg/common/consumer/consumer_manager_test.go
- pkg/common/consumer/consumergroup_offsets_checker.go
- pkg/common/consumer/testing/mocks.go
- pkg/source/adapter/adapter.go
Fixes #
- Fixing some issues created during https://github.com/knative-sandbox/eventing-kafka/pull/886
- Applying the fixes from https://github.com/aliok/eventing-kafka/pull/1 (that was on main)
- Change offset checking loop
- Requeue channel when there's a failure in the loop
```release-note
- 🐛  Fixed an issue with the offset checking in the dispatcher so that the reconciliation is more proper
```
**Docs**
> [0.24] KafkaChannel dispatcher offset checking improvements

- cmd/channel/distributed/dispatcher/main.go
- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
- pkg/channel/consolidated/dispatcher/dispatcher_test.go
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel.go
- pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
- pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
- pkg/common/consumer/consumer_factory.go
- pkg/common/consumer/consumer_factory_test.go
- pkg/common/consumer/consumer_handler.go
- pkg/common/consumer/consumer_manager.go
- pkg/common/consumer/consumer_manager_test.go
- pkg/common/consumer/consumergroup_offsets_checker.go
- pkg/common/consumer/testing/mocks.go
- pkg/source/adapter/adapter.go
Fixes #
- Backport https://github.com/knative-sandbox/eventing-kafka/pull/928
-
-
```release-note
```
**Docs**
> [0.25] KafkaChannel dispatcher offset checking improvements

- .golangci.yaml
- pkg/channel/consolidated/reconciler/controller/controller.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/distributed/controller/kafkachannel/controller.go
- pkg/common/scheduler/statefulset/scheduler.go
- test/e2e/helpers/kafka_source_test_helper.go
As per title, this introduces a few new linters that come via Eventing.
**Note:** We should take a look at enabling `gosec`, but it had a few complaints I was not comfortable fixing without context.
```release-note
NONE
```
**Docs**
> Add linters that are used in eventing

- pkg/apis/sources/v1beta1/kafka_defaults.go
- pkg/apis/sources/v1beta1/kafka_defaults_test.go
Sink namespace is not defaulted to the object namespace for:
- KafkaSource
Forcing every implementation to define the logic:
"If `spec.sink.ref.namespace` is empty, use `metadata.namespace`"
Similar to https://github.com/knative/eventing/pull/5748
- Default KafkaSource sink namespace to object namespace
```release-note
The field `spec.sink.ref.namespace` for `KafkaSource` if not specified is defaulted to `metadata.namespace`.
```
**Docs**
```
None
```
/cc @aliok @matzew @lionelvillard
> Default KafkaSource sink ref namespace to object namespace

- config/channel/post-install/storage-version-migrator.yaml
- config/source/post-install/storage-version-migrator.yaml
This broke because of Golang 1.17 with the following error
```
package knative.dev/eventing-kafka/vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate imports k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset from implicitly required module; to add missing requirements, run:
go get k8s.io/apiextensions-apiserver@v0.21.4
```
This change is in-line with what we did to other repos.
Nightly is broken because of this.
> Fix post install jobs golang path

- go.mod
- go.sum
- vendor/knative.dev/hack/library.sh
- vendor/knative.dev/hack/release.sh
- vendor/modules.txt
Due to recent dependency upgrades at eventing, [this automation](https://github.com/knative-sandbox/actions-downstream-test/blob/a4435de6e0c02b32bcd9338873f63ce2eb9cc4ad/action.yaml#L16-L21) is resolving samara to 1.30.0.
```console
2021-11-05T10:38:04.2440777Z ##[group]Run pushd ./src/knative.dev/eventing-kafka-broker
2021-11-05T10:38:04.2441767Z [36;1mpushd ./src/knative.dev/eventing-kafka-broker[0m
2021-11-05T10:38:04.2442770Z [36;1mgo mod edit -replace knative.dev/eventing=$GITHUB_WORKSPACE/src/knative.dev/eventing[0m
2021-11-05T10:38:04.2443521Z [36;1mpopd[0m
2021-11-05T10:38:04.2487470Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2021-11-05T10:38:04.2488040Z env:
2021-11-05T10:38:04.2488655Z   GOPATH: /home/runner/work/eventing/eventing …
```
> Pin sarama version to v1.29.1

- test/e2e/helpers/kafka_source_test_helper.go
- test/e2e/kafka_source_test.go
- test/lib/creation.go
The sleep is causing flaky tests in eventing-kafka-broker and
in this repository (as the skip suggests)
Fixes a TODO
- Remove sleep and wait for KafkaSource reconciliation
```release-note
None
```
**Docs**
```
None
```
> Remove sleep and wait for KafkaSource reconciliation

- test/lib/creation.go
Mitigation for https://github.com/knative/pkg/issues/1509.
Same fix was used in eventing core to mitigate webhook EOF
errors.
Fixes (some flaky tests in eventing-kafka-broker)
- Retry on Webhook EOF Errors
```release-note
None
```
**Docs**
```
None
```
> Retry on Webhook EOF Errors

- test/e2e/helpers/kafka_helper.go
- test/e2e/helpers/kafka_source_test_helper.go
- Check KafkaSource IsReady before moving on to the next step.
- Increase waiting for resource ready timeout since errors like:
```
{
"lastTransitionTime": "2021-11-22T07:08:42.968600Z",
"message": "This server does not host this topic-partition.",
"reason": "UnknownTopicOrPartitionException",
"status": "True",
"type": "NotReady"
}
```
seems to take longer to resolve.
```release-note
None
```
**Docs**
```
None
```
> Add IsReady & Increase timeout to KafkaSource tests

- pkg/common/tracing/tracing_test.go
Stupid oversight in recent creation of unit tests for tracing utility functions.  Was order dependent when should not have been.  Crazy it has been passing for this long ; )
- 🐛  Fix testify assertion utilities used to compare array contents.
```release-note
```
**Docs**
> Fix array comparison in tracing unit test.

- test/conformance/source_crd_registry_test.go
> SourceCRDRegistryTest

- config/channel/resources/kafkachannel-crd.yaml
In order to allow experimental-features related to the Delivery Spec (Timeout, RetryAfterMax, etc.) we need to loosen constraints on that part of the KafkaChannel CRD.
- 🧽  Add preserve-unknown-fields flag to "delivery" portions of the KafkaChannel CRD.
```release-note
```
**Docs**
> Update KafkaChannel CRD to support experimental-features in Delivery

- pkg/apis/sources/v1beta1/kafka_validation.go
- test/e2e/helpers/kafka_source.go
We need to validate the SourceSpec field as part of the KafkaSource
webhook validation.
The E2E test for KafkaSource is trying specify the type as
`CEOverride` which is disallowed by the Source spec:
> When spec.ceOverrides.extensions is specified and non-empty,
> the event sent to the sink is augmented or modified with the
> specified extension attributes.
> The source controller MUST reject extensions overriding the
> required Cloud Events attributes.
Ref: https://github.com/knative/eventing/blob/main/docs/spec/sources.md#duckspec
Signed-off-by: Pierangelo Di Pilato <pdipilat@redhat.com>
Part of upgrading dependencies in #1035
```release-note
The KafkaSource webhook reject extensions overriding the required Cloud Events attributes as specified by the SourceSpec …
```
> Validate SourceSpec in KafkaSource

- pkg/common/consumer/consumer_factory.go
- pkg/common/consumer/consumer_manager.go
- pkg/common/consumer/consumer_manager_test.go
- pkg/common/consumer/managed_group.go
- pkg/common/consumer/managed_group_test.go
Fixes #1043
- 🐛 ConsumerGroup manager was only reading from the ConsumerGroup error channel and not the merged channel from the KafkaConsumerGroupFactory.  This has been rectified.
Note:  As this is potentially a large problem and the fix is relatively small, this fix should be back-ported
> Consumer manager use factory merged errors

- pkg/common/consumer/consumer_manager_test.go
- pkg/common/consumer/managed_group_test.go
- 🧽  The PR that fixes #1043 (#1044) seems to be introducing some race conditions that are very sporadic and related to logging being done after a test finishes.  This PR should fix that by allowing the goroutine involved to exit before leaving the testing scope.
> Attempting to un-flaky the tests that use the zap test logger

- pkg/common/consumer/consumer_factory.go
- pkg/common/consumer/consumer_manager.go
- pkg/common/consumer/consumer_manager_test.go
- pkg/common/consumer/managed_group.go
- pkg/common/consumer/managed_group_test.go
* ConsumerGroup Manager-use factory merged errors channel (fix for #1043)
This is a cherry-pick of #1044
> [release-1.1] Consumer manager use factory merged errors (#1044)

- go.mod
- go.sum
- pkg/common/consumer/consumer_factory.go
- pkg/common/consumer/consumer_manager.go
- pkg/common/consumer/consumer_manager_test.go
- pkg/common/consumer/managed_group.go
- pkg/common/consumer/managed_group_test.go
- vendor/knative.dev/hack/library.sh
- vendor/knative.dev/hack/release.sh
- vendor/modules.txt
* ConsumerGroup Manager-use factory merged errors channel (fix for #1043)
This is a cherry-pick of #1044
> [release-1.0] Consumer manager use factory merged errors (#1044)

- config/channel/resources/kafkachannel-crd.yaml
Fixes #1056
- Define status.deadLetterSinkUri in KafkaChannel CRD
-
-
```release-note
```
**Docs**
> Define status.deadLetterSinkUri in KafkaChannel CRD

- config/channel/config/leader-election-configmap.yaml
- config/channel/consolidated/400-leaderelection-configmap.yaml
- config/channel/consolidated/deployments/controller.yaml
- config/channel/distributed/300-leaderelection-configmap.yaml
- config/channel/distributed/500-controller-deployment.yaml
- config/channel/webhook/webhook-deployment-ro.yaml
- config/channel/webhook/webhook-deployment.yaml
The semi-recent automated update of dependencies #1058 pulled in changes in **knative.dev/pkg/leader-election/config.go** which are breaking the startup of the KafkaChannel Webhook.  Specifically the default config timings were relaxed to be less frequent...
```
func defaultConfig() *Config {
return &Config{
Buckets:       1,
LeaseDuration: 60 * time.Second,
RenewDeadline: 40 * time.Second,
RetryPeriod:   10 * time.Second,
}
}
```
The KafkaChannel Webhook deployment has a 20 second delay on the initial liveness probe...
```
livenessProbe:
<<: *probe
initialDelaySeconds: 20
```
So the webhook is restarted continually before it can finish the leader election setup.
This is a problem when uninstalling and re-installing in an existing namespace as the leases are not removed.  If the namespace …
> Custom leader-election configuration for KafkaChannel

- test/e2e-tests.sh
This fixes e2e-tests.sh failures in CI since the CI images don't include ps command. We discuss if we want to actually continue using ps in this manner, but this is needed now for unblocking 1.2 release
- 🐛 Install ps command if not available in e2e tests runner script
> Check if ps is not installed and install it

- test/upgrade/continual/kafkasender.go
Fixes #1103
- Reduce the replica acknowledgements from WaitForAll to WaitForLocal for the KafkaSender in upgrade tests
```release-note
```
**Docs**
> Prevent excessive wait time in KafkaSender for upgrade tests

- pkg/source/reconciler/source/resources/receive_adapter.go
Fixes #1008
- 🧽 Limit single-tenant Kafka source use of resources such as CPU and memory
```release-note
```
**Docs**
> Set resource limit for single-tenant Kafka source

- pkg/channel/consolidated/dispatcher/consumer_message_handler.go
- pkg/channel/distributed/dispatcher/dispatcher/handler.go
- pkg/common/tracing/tracing.go
- pkg/common/tracing/tracing_test.go
- pkg/source/adapter/adapter.go
Fixes #1105
- KafkaSource continues Zipkin traces stored in message headers.
- 🐛 Fix bug
The Trace is now visible from the start while previously it was starting at Kafka source
```release-note
```
**Docs**
> KafkaSource continues Trace from messages

- config/source/common/configmaps/config-descheduler.yaml
- config/source/common/configmaps/config-scheduler.yaml
- config/source/multi/deployments/controller.yaml
- pkg/source/reconciler/mtsource/controller.go
Signed-off-by: aavarghese <avarghese@us.ibm.com>
Removing `MAXFILLUP` scheduling strategy and replacing with [Multi-Tenant HA Scheduler](https://github.com/knative/eventing/tree/main/pkg/scheduler)
> Activating HA scheduler for scaling and scheduling KafkaSource consumers

- test/e2e/helpers/kafka_source_test_helper.go
Using the same consumer group for the different sources might produce
unreliable results because Kafka group ids are shared.
This is particularly evident in eventing-kafka-broker where the same
tests (`KafkaSourceUpdate`) is executed 5 times [1] in parallel [2]
(to catch flakes early), which means that there might be different
sources with the same consumer group pointing to 2 different sinks.
[1] https://github.com/knative-sandbox/eventing-kafka-broker/blob/e169e2cb923890a23e8d65651876292283b63908/test/e2e/kafka_source_test.go#L31
[2] https://github.com/knative-sandbox/eventing-kafka-broker/blob/e169e2cb923890a23e8d65651876292283b63908/test/pkg/testing/run.go#L52-L67
Signed-off-by: Pierangelo Di Pilato <pdipilat@redhat.com>
> Generate consumer group in KafkaSourceUpdate test

- test/e2e-common.sh
This PR is to add a flag `KO_FLAGS` to the e2e test. This opens up a chance to set other KO options (e.g. `--platform`). 
- add KO_FLAGS to `ko apply`
```release-note
```
**Docs**
> Add KO_FLAGS to e2e test

- test/upgrade/continual/channel.go
Fixes #
- Follow up for https://github.com/knative/eventing/pull/5875
-
-
```release-note
```
**Docs**
> The channelTemplateSpec: is deprecated and replaced by channel-template-spec

- pkg/channel/consolidated/reconciler/controller/resources/service.go
- pkg/channel/consolidated/reconciler/controller/resources/service_test.go
Appending a suffix to the service associated with a KafkaChannel
cannot be done when the resulting name is too long.
Signed-off-by: Pierangelo Di Pilato <pdipilat@redhat.com>
```release-note
Correctly handle KafkaChannels with long names
```
**Docs**
> Correctly handle KafkaChannels with long names

- test/e2e/helpers/kafka_helper.go
Fixes #
- `MustCreateKafkaUserForTopic` now takes authType as well 
```release-note
`MustCreateKafkaUserForTopic` now takes authType as well 
```
**Docs**
> Adding authType argument

- pkg/common/kafka/offset/offsets.go
The OffsetManager wasn't closed after initializing the offsets
leading to go routing leaks.
Signed-off-by: Pierangelo Di Pilato <pdipilat@redhat.com>
Fixes https://github.com/knative-sandbox/eventing-kafka-broker/issues/2417
```release-note
The OffsetManager wasn't closed after initializing the offsets leading to go routing leaks.
```
> Close OffsetManager on init offsets

- config/channel/webhook/webhook-hpa.yaml
Fixes #
- Use PodDisruptionBudget v1
- Need to fix this old release as there are issues when we try `eventing-kafka` with newer Kubernetes versions
-
```release-note
🐛 Upgrade PodDisruptionBudget used in KafkaChannel webhook from policy/v1beta1 to policy/v1
```
**Docs**
> [1.5] Use PodDisruptionBudget v1

- config/channel/webhook/webhook-hpa.yaml
The [nightly release job](https://prow.knative.dev/view/gs/knative-prow/logs/nightly_eventing-kafka_main_periodic/1616369505573801984) has some issues with deprecated APIs on upgrade jobs:
```
Jan 20 10:02:44.846 install_released_consolidated_channel [OUT] Applying: /logs/artifacts/channel-consolidated-knative-v1.8.1.yaml
...
Jan 20 10:02:50.925 install_released_consolidated_channel [ERR] Warning: autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
Jan 20 10:02:51.081 install_released_consolidated_channel [OUT] horizontalpodautoscaler.autoscaling/kafka-webhook created
...
Jan 20 10:02:51.298 install_released_consolidated_channel [ERR] error: resource mapping not found for name: "kafka-webhook" namespace: …
```
> Update API versions of HorizontalPodAutoscaler and PodDisruptionBudget

- pkg/source/adapter/adapter.go
- pkg/source/adapter/adapter_test.go
- pkg/source/adapter/message.go
Switch usage from the "old" message sender to using `kncloudevents.SendEvent()`.
> Remove usage of deprecated kncloudevents.CloudEventsRequest

- go.mod
- go.sum
- pkg/source/reconciler/mtsource/controller.go
- vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
- vendor/modules.txt
- bump to latest
- remove depracted function usage of statefulset scheduler (as per https://github.com/knative/eventing/pull/6736)
```release-note
```
**Docs**
> Manually bump to latest

- pkg/source/mtadapter/adapter.go
Fixes the failing integration tests
- Add the kubeclient into the context used to create the new adapter in the Update function
> Added kubeclient to context for new adapter creation

- go.mod
- go.sum
Seeing issues in #1460. Updating golang in go.mod helped in other cases
> Update Golang in go.mod to 1.21
